import { defineSchema, defineTable } from "convex/server";
import { v } from "convex/values";

export default defineSchema({
  demo_auditEvents: defineTable({
    actorPersona: v.string(),
    afterSummary: v.optional(v.string()),
    beforeSummary: v.optional(v.string()),
    buildId: v.optional(v.id("demo_builds")),
    command: v.string(),
    correlationId: v.string(),
    createdAt: v.number(),
    drawGroupKey: v.optional(v.string()),
    entityKey: v.optional(v.string()),
    entityLabel: v.optional(v.string()),
    entityType: v.string(),
    eventType: v.string(),
    milestoneKey: v.optional(v.string()),
    reason: v.optional(v.string()),
    scenario: v.string(),
    validation: v.string(),
  })
    .index("by_scenario", ["scenario"])
    .index("by_milestone", ["scenario", "milestoneKey"])
    .index("by_draw_group", ["scenario", "drawGroupKey"]),
  demo_builds: defineTable({
    flatDrawFeeCents: v.number(),
    interestAnnualBps: v.number(),
    key: v.string(),
    lenderDrawPolicyLimitCents: v.number(),
    name: v.string(),
    payoffDate: v.string(),
    projectStartDate: v.string(),
    scenario: v.string(),
    seedVersion: v.number(),
    status: v.string(),
    subtitle: v.string(),
    submittedAt: v.optional(v.number()),
    todayDate: v.string(),
    updatedAt: v.number(),
    workingCapitalLimitCents: v.number(),
  })
    .index("by_key", ["key"])
    .index("by_scenario", ["scenario"]),
  demo_drawGroups: defineTable({
    approvedValueCents: v.number(),
    baselineEndDate: v.optional(v.string()),
    baselineStartDate: v.optional(v.string()),
    buildId: v.id("demo_builds"),
    forecastEndDate: v.optional(v.string()),
    forecastStartDate: v.optional(v.string()),
    key: v.string(),
    label: v.string(),
    order: v.number(),
    plannedEndDate: v.optional(v.string()),
    plannedStartDate: v.optional(v.string()),
    releaseApprovedAt: v.optional(v.number()),
    requestedValueCents: v.number(),
    scenario: v.string(),
    status: v.string(),
    updatedAt: v.number(),
  })
    .index("by_build_order", ["buildId", "order"])
    .index("by_scenario", ["scenario"])
    .index("by_scenario_key", ["scenario", "key"]),
  demo_eventOutbox: defineTable({
    buildId: v.optional(v.id("demo_builds")),
    createdAt: v.number(),
    drawGroupKey: v.optional(v.string()),
    eventType: v.string(),
    milestoneKey: v.optional(v.string()),
    payloadPreview: v.string(),
    relatedEntity: v.string(),
    scenario: v.string(),
    status: v.string(),
  })
    .index("by_scenario", ["scenario"])
    .index("by_milestone", ["scenario", "milestoneKey"]),
  demo_evidenceFiles: defineTable({
    buildId: v.id("demo_builds"),
    evidencePackageId: v.optional(v.id("demo_evidencePackages")),
    fileName: v.string(),
    isSample: v.boolean(),
    milestoneId: v.id("demo_milestones"),
    milestoneKey: v.string(),
    mimeType: v.string(),
    removedAt: v.optional(v.number()),
    scenario: v.string(),
    sizeBytes: v.number(),
    uploadedAt: v.number(),
    uploadedByPersona: v.string(),
  })
    .index("by_milestone", ["scenario", "milestoneKey"])
    .index("by_package", ["evidencePackageId"]),
  demo_evidencePackages: defineTable({
    buildId: v.id("demo_builds"),
    createdAt: v.number(),
    frozenAt: v.optional(v.number()),
    milestoneId: v.id("demo_milestones"),
    milestoneKey: v.string(),
    reviewStatus: v.string(),
    scenario: v.string(),
    status: v.string(),
    submittedAt: v.optional(v.number()),
  })
    .index("by_milestone", ["scenario", "milestoneKey"])
    .index("by_scenario", ["scenario"]),
  demo_forecastUpdates: defineTable({
    actorPersona: v.string(),
    buildId: v.id("demo_builds"),
    createdAt: v.number(),
    milestoneId: v.id("demo_milestones"),
    milestoneKey: v.string(),
    newEndDate: v.string(),
    newStartDate: v.string(),
    priorEndDate: v.string(),
    priorStartDate: v.string(),
    reason: v.string(),
    scenario: v.string(),
  }).index("by_milestone", ["scenario", "milestoneKey"]),
  demo_milestoneDependencies: defineTable({
    blockedKey: v.string(),
    blockerKey: v.string(),
    buildId: v.id("demo_builds"),
    isSystem: v.boolean(),
    scenario: v.string(),
    severity: v.string(),
    type: v.string(),
  })
    .index("by_blocked", ["scenario", "blockedKey"])
    .index("by_blocker", ["scenario", "blockerKey"])
    .index("by_scenario", ["scenario"]),
  demo_milestones: defineTable({
    actualCompletedDate: v.optional(v.string()),
    approvedAt: v.optional(v.number()),
    approvedByPersona: v.optional(v.string()),
    approvedValueCents: v.number(),
    baselineEndDate: v.optional(v.string()),
    baselineStartDate: v.optional(v.string()),
    buildId: v.id("demo_builds"),
    code: v.string(),
    drawGroupKey: v.string(),
    durationDays: v.number(),
    evidenceReviewStatus: v.optional(v.string()),
    forecastEndDate: v.optional(v.string()),
    forecastStartDate: v.optional(v.string()),
    isDragLocked: v.optional(v.boolean()),
    key: v.string(),
    name: v.string(),
    order: v.number(),
    plannedEndDate: v.optional(v.string()),
    plannedStartDate: v.optional(v.string()),
    progressPercent: v.number(),
    requestedAmountCents: v.optional(v.number()),
    requiresSiteVisit: v.boolean(),
    scenario: v.string(),
    status: v.string(),
    submittedAt: v.optional(v.number()),
    type: v.string(),
    updatedAt: v.number(),
  })
    .index("by_build_order", ["buildId", "order"])
    .index("by_draw_group", ["scenario", "drawGroupKey"])
    .index("by_key", ["scenario", "key"])
    .index("by_scenario", ["scenario"]),
  demo_planningRuns: defineTable({
    buildId: v.id("demo_builds"),
    createdAt: v.number(),
    errors: v.array(v.string()),
    interestEstimateCents: v.number(),
    recommendedDrawCount: v.number(),
    recommendedOrderKeys: v.array(v.string()),
    runType: v.string(),
    scenario: v.string(),
    status: v.string(),
    warnings: v.array(v.string()),
  }).index("by_scenario", ["scenario"]),
  demo_warningDismissals: defineTable({
    actorPersona: v.string(),
    conditionHash: v.string(),
    dismissedAt: v.number(),
    drawGroupKey: v.optional(v.string()),
    milestoneKey: v.optional(v.string()),
    reason: v.optional(v.string()),
    scenario: v.string(),
    warningCode: v.string(),
    warningId: v.string(),
  })
    .index("by_scenario", ["scenario"])
    .index("by_warning", ["scenario", "warningId", "conditionHash"]),
  demo_policySnapshots: defineTable({
    buildId: v.id("demo_builds"),
    createdAt: v.number(),
    flatDrawFeeCents: v.number(),
    interestAnnualBps: v.number(),
    scenario: v.string(),
    workingCapitalLimitCents: v.number(),
  }).index("by_scenario", ["scenario"]),
  demo_reviewReports: defineTable({
    buildId: v.id("demo_builds"),
    createdAt: v.number(),
    milestoneId: v.id("demo_milestones"),
    milestoneKey: v.string(),
    notes: v.string(),
    outcome: v.string(),
    reviewerPersona: v.string(),
    scenario: v.string(),
  }).index("by_milestone", ["scenario", "milestoneKey"]),
  demo_rolloverBuffers: defineTable({
    buildId: v.id("demo_builds"),
    createdAt: v.number(),
    milestoneId: v.id("demo_milestones"),
    milestoneKey: v.string(),
    originalApprovedCents: v.number(),
    requestedAmountCents: v.number(),
    scenario: v.string(),
    status: v.string(),
    unusedAmountCents: v.number(),
  }).index("by_scenario", ["scenario"]),
  demo_siteVisits: defineTable({
    assignedPersona: v.string(),
    buildId: v.id("demo_builds"),
    claimedAt: v.optional(v.number()),
    completedAt: v.optional(v.number()),
    completionObserved: v.optional(v.boolean()),
    createdAt: v.number(),
    milestoneId: v.id("demo_milestones"),
    milestoneKey: v.string(),
    notes: v.optional(v.string()),
    recommendedOutcome: v.optional(v.string()),
    riskFlags: v.optional(v.array(v.string())),
    scenario: v.string(),
    status: v.string(),
  })
    .index("by_milestone", ["scenario", "milestoneKey"])
    .index("by_scenario", ["scenario"]),
  products: defineTable({
    title: v.string(),
    imageId: v.string(),
    price: v.number(),
  }),
  todos: defineTable({
    text: v.string(),
    completed: v.boolean(),
  }),
  users: defineTable({
    authId: v.string(),
    email: v.string(),
    name: v.string(),
  }).index("authId", ["authId"]),
});
