import { corePages } from "./fairlend-public-core-content";
import type {
  IntakePage,
  IntakePageId,
} from "./fairlend-public-content-types";

export const intakePages: Record<IntakePageId, IntakePage> = {
  start: {
    id: "start",
    path: "/start",
    title: "Start with Fairlend",
    description:
      "Choose the right Fairlend intake path for your project, investment, referral, media, or general inquiry.",
    headline: "Start in the right lane.",
    deck: "Fairlend routes each inquiry by project type, capital need, and urgency so the first review is useful.",
    parentHref: "/contact",
    brandKit: corePages.contact.brandKit,
    fields: [],
    routes: [
      {
        title: "I want to build a multiplex",
        copy: "Unit count, budget, permit stage, and financing structure.",
        href: "/start/multiplex",
      },
      {
        title: "I want to build a garden suite",
        copy: "Property, equity, design status, and rental plan.",
        href: "/start/garden-suite",
      },
      {
        title: "I am a builder",
        copy: "Upcoming projects, draw needs, locations, and active build volume.",
        href: "/start/builder",
      },
      {
        title: "I am a broker or referral partner",
        copy: "Client fit, referral context, and desired next step.",
        href: "/start/broker",
      },
      {
        title: "I want investor information",
        copy: "Investor profile, experience, intended allocation, and consent.",
        href: "/start/investor",
      },
      {
        title: "I am a journalist",
        copy: "Topic, deadline, requested format, and media contact details.",
        href: "/start/media",
      },
    ],
  },
  startMultiplex: {
    id: "startMultiplex",
    path: "/start/multiplex",
    title: "Multiplex Project Intake",
    description:
      "Submit a GTA multiplex project for Fairlend feasibility review.",
    headline: "Tell us enough to assess the multiplex path.",
    deck: "The first review needs the property, unit plan, permit stage, budget, ownership, mortgage context, and timeline.",
    parentHref: "/multiplex-financing-gta",
    brandKit: corePages.multiplex.brandKit,
    fields: [
      { label: "Name", required: true },
      { label: "Email", type: "email", required: true },
      { label: "Phone", type: "tel" },
      { label: "Property address", required: true },
      { label: "Existing property type" },
      { label: "Proposed number of units", type: "number" },
      {
        label: "New build or conversion",
        type: "select",
        options: ["New build", "Conversion", "Addition", "Mixed scope"],
      },
      {
        label: "Permit status",
        type: "select",
        options: ["Not started", "Design underway", "Submitted", "Issued"],
      },
      { label: "Estimated project budget" },
      { label: "Land owned or under contract" },
      { label: "Current mortgage balance" },
      { label: "Desired timeline" },
      { label: "Upload drawings, pro forma, or budget", type: "file" },
      { label: "Project notes", type: "textarea" },
    ],
  },
  startGardenSuite: {
    id: "startGardenSuite",
    path: "/start/garden-suite",
    title: "Garden Suite Intake",
    description:
      "Submit a garden suite or laneway suite property for Fairlend financing review.",
    headline: "Check whether the property can carry the suite.",
    deck: "The first review looks at address, equity, existing debt, permit status, construction budget, intended rental use, and timing.",
    parentHref: "/garden-suite-financing-gta",
    brandKit: corePages.gardenSuite.brandKit,
    fields: [
      { label: "Name", required: true },
      { label: "Email", type: "email", required: true },
      { label: "Property address", required: true },
      { label: "Existing home type" },
      { label: "Lot size, if known" },
      { label: "Current mortgage balance" },
      { label: "Approximate equity" },
      {
        label: "Permit or design status",
        type: "select",
        options: [
          "Idea stage",
          "Designer engaged",
          "Permit submitted",
          "Permit issued",
        ],
      },
      { label: "Estimated construction budget" },
      { label: "Intended rental use" },
      { label: "Timeline" },
      { label: "Notes", type: "textarea" },
    ],
  },
  startBuilder: {
    id: "startBuilder",
    path: "/start/builder",
    title: "Builder Project Intake",
    description:
      "Submit upcoming builder projects and draw schedule requirements for Fairlend review.",
    headline: "Map the upcoming builds before draw pressure hits.",
    deck: "Fairlend reviews project type, build volume, locations, permits, financing need, draw schedule requirements, and typical project size.",
    parentHref: "/construction-draw-financing",
    brandKit: corePages.drawFinancing.brandKit,
    fields: [
      { label: "Company name", required: true },
      { label: "Primary contact", required: true },
      { label: "Email", type: "email", required: true },
      { label: "Project type" },
      { label: "Number of active or upcoming builds", type: "number" },
      { label: "Locations" },
      { label: "Unit count" },
      { label: "Permit status" },
      { label: "Financing needed" },
      { label: "Draw schedule requirements", type: "textarea" },
      { label: "Typical project size" },
      { label: "Additional context", type: "textarea" },
    ],
  },
  startInvestor: {
    id: "startInvestor",
    path: "/start/investor",
    title: "Investor Information Request",
    description:
      "Request Fairlend investor information with profile, experience, intended allocation, and consent acknowledgment.",
    headline: "Request investor information through a compliant first step.",
    deck: "This intake captures investor type, experience, intended allocation, interest area, contact details, and acknowledgement.",
    parentHref: "/investors",
    brandKit: corePages.investors.brandKit,
    compliance:
      "This request is informational and is not an offer to sell securities. Suitability and eligibility require separate review.",
    fields: [
      { label: "Name", required: true },
      { label: "Email", type: "email", required: true },
      {
        label: "Investor type",
        type: "select",
        options: [
          "Individual",
          "Accredited investor",
          "Family office",
          "Advisor",
          "Institution",
        ],
      },
      { label: "Investment experience" },
      { label: "Approximate intended allocation" },
      { label: "Interest area" },
      { label: "Phone", type: "tel" },
      {
        label: "Consent and disclaimer acknowledgment",
        type: "checkbox",
        required: true,
      },
      { label: "Questions", type: "textarea" },
    ],
  },
  startBroker: {
    id: "startBroker",
    path: "/start/broker",
    title: "Broker and Referral Partner Intake",
    description:
      "Route broker and referral partner inquiries to Fairlend with client and project context.",
    headline: "Bring the client context, not just the lead.",
    deck: "Referral quality improves when the first note includes project type, financing need, stage, location, and timeline.",
    parentHref: "/contact",
    brandKit: corePages.contact.brandKit,
    fields: [
      { label: "Name", required: true },
      { label: "Email", type: "email", required: true },
      { label: "Company" },
      {
        label: "Referral type",
        type: "select",
        options: ["Multiplex", "Garden suite", "Builder", "Investor", "Other"],
      },
      { label: "Client or project location" },
      { label: "Financing need" },
      { label: "Timeline" },
      { label: "Referral context", type: "textarea" },
    ],
  },
  startMedia: {
    id: "startMedia",
    path: "/start/media",
    title: "Media Inquiry",
    description:
      "Submit a media inquiry, deadline, topic, and requested interview or quote format for Fairlend.",
    headline: "Give the media team the deadline and the angle.",
    deck: "Fairlend can respond faster when the request includes publication, topic, deadline, format, and requested spokesperson.",
    parentHref: "/press",
    brandKit: corePages.press.brandKit,
    fields: [
      { label: "Name", required: true },
      { label: "Email", type: "email", required: true },
      { label: "Publication or organization" },
      { label: "Topic" },
      { label: "Deadline" },
      {
        label: "Requested format",
        type: "select",
        options: [
          "Written quote",
          "Phone interview",
          "Video interview",
          "Background context",
        ],
      },
      { label: "Questions or brief", type: "textarea" },
    ],
  },
};

