/* eslint-disable */
/**
 * Generated `api` utility.
 *
 * THIS CODE IS AUTOMATICALLY GENERATED.
 *
 * To regenerate, run `npx convex dev`.
 * @module
 */

import type * as activeBuildAccess from "../activeBuildAccess.js";
import type * as active_build_document_lineage from "../active_build_document_lineage.js";
import type * as administrative_override_policy from "../administrative_override_policy.js";
import type * as assistant from "../assistant.js";
import type * as assistant_access from "../assistant/access.js";
import type * as assistant_action_handlers from "../assistant/action_handlers.js";
import type * as assistant_action_mutations from "../assistant/action_mutations.js";
import type * as assistant_action_preview from "../assistant/action_preview.js";
import type * as assistant_briefing from "../assistant/briefing.js";
import type * as assistant_contracts from "../assistant/contracts.js";
import type * as assistant_inputs from "../assistant/inputs.js";
import type * as assistant_mutations from "../assistant/mutations.js";
import type * as assistant_planning from "../assistant/planning.js";
import type * as assistant_shared from "../assistant/shared.js";
import type * as assistant_tool_definitions from "../assistant/tool_definitions.js";
import type * as assistant_workflow_handlers from "../assistant/workflow_handlers.js";
import type * as assistantProvider from "../assistantProvider.js";
import type * as audit_event_migrations from "../audit_event_migrations.js";
import type * as auth from "../auth.js";
import type * as authz from "../authz.js";
import type * as authzTest from "../authzTest.js";
import type * as brokerAssignments from "../brokerAssignments.js";
import type * as brokerageProvisioning from "../brokerageProvisioning.js";
import type * as brokerageProvisioning_provisioning from "../brokerageProvisioning/provisioning.js";
import type * as brokerageProvisioning_relationship from "../brokerageProvisioning/relationship.js";
import type * as build_action_item_application from "../build_action_item_application.js";
import type * as build_action_item_deadline_migrations from "../build_action_item_deadline_migrations.js";
import type * as build_action_item_deadline_model from "../build_action_item_deadline_model.js";
import type * as build_action_item_details from "../build_action_item_details.js";
import type * as build_action_item_governance from "../build_action_item_governance.js";
import type * as build_action_item_history from "../build_action_item_history.js";
import type * as build_action_item_post_links from "../build_action_item_post_links.js";
import type * as build_action_item_queue_projection from "../build_action_item_queue_projection.js";
import type * as build_action_item_queues from "../build_action_item_queues.js";
import type * as build_action_item_queues_helpers from "../build_action_item_queues/helpers.js";
import type * as build_action_item_rbac from "../build_action_item_rbac.js";
import type * as build_action_item_structure from "../build_action_item_structure.js";
import type * as build_action_item_structure_helpers from "../build_action_item_structure/helpers.js";
import type * as build_action_item_structure_model from "../build_action_item_structure_model.js";
import type * as build_action_item_tags from "../build_action_item_tags.js";
import type * as build_action_item_workflow from "../build_action_item_workflow.js";
import type * as build_action_item_workflow_policy from "../build_action_item_workflow/policy.js";
import type * as build_action_items from "../build_action_items.js";
import type * as build_action_items_helpers from "../build_action_items/helpers.js";
import type * as build_collaboration from "../build_collaboration.js";
import type * as build_collaboration_helpers from "../build_collaboration/helpers.js";
import type * as build_collaboration_access from "../build_collaboration_access.js";
import type * as build_collaboration_acknowledgements from "../build_collaboration_acknowledgements.js";
import type * as build_collaboration_actor from "../build_collaboration_actor.js";
import type * as build_collaboration_archive from "../build_collaboration_archive.js";
import type * as build_collaboration_archive_action_items from "../build_collaboration_archive/action_items.js";
import type * as build_collaboration_archive_common from "../build_collaboration_archive/common.js";
import type * as build_collaboration_archive_contracts from "../build_collaboration_archive/contracts.js";
import type * as build_collaboration_archive_moderation from "../build_collaboration_archive/moderation.js";
import type * as build_collaboration_archive_revision from "../build_collaboration_archive/revision.js";
import type * as build_collaboration_asset_access from "../build_collaboration_asset_access.js";
import type * as build_collaboration_asset_actions from "../build_collaboration_asset_actions.js";
import type * as build_collaboration_asset_maintenance from "../build_collaboration_asset_maintenance.js";
import type * as build_collaboration_asset_projection from "../build_collaboration_asset_projection.js";
import type * as build_collaboration_asset_publication from "../build_collaboration_asset_publication.js";
import type * as build_collaboration_asset_upload_application from "../build_collaboration_asset_upload_application.js";
import type * as build_collaboration_assets from "../build_collaboration_assets.js";
import type * as build_collaboration_assets_helpers from "../build_collaboration_assets/helpers.js";
import type * as build_collaboration_content from "../build_collaboration_content.js";
import type * as build_collaboration_contracts from "../build_collaboration_contracts.js";
import type * as build_collaboration_cutover_certification from "../build_collaboration_cutover_certification.js";
import type * as build_collaboration_cutover_rehearsals from "../build_collaboration_cutover_rehearsals.js";
import type * as build_collaboration_delivery from "../build_collaboration_delivery.js";
import type * as build_collaboration_delivery_api from "../build_collaboration_delivery_api.js";
import type * as build_collaboration_delivery_maintenance from "../build_collaboration_delivery_maintenance.js";
import type * as build_collaboration_delivery_maintenance_attempts from "../build_collaboration_delivery_maintenance/attempts.js";
import type * as build_collaboration_delivery_maintenance_contracts from "../build_collaboration_delivery_maintenance/contracts.js";
import type * as build_collaboration_delivery_maintenance_helpers from "../build_collaboration_delivery_maintenance/helpers.js";
import type * as build_collaboration_delivery_maintenance_preparation from "../build_collaboration_delivery_maintenance/preparation.js";
import type * as build_collaboration_delivery_model from "../build_collaboration_delivery_model.js";
import type * as build_collaboration_delivery_reconciliation from "../build_collaboration_delivery_reconciliation.js";
import type * as build_collaboration_delivery_transport from "../build_collaboration_delivery_transport.js";
import type * as build_collaboration_delivery_transport_provider from "../build_collaboration_delivery_transport_provider.js";
import type * as build_collaboration_drafts from "../build_collaboration_drafts.js";
import type * as build_collaboration_editing from "../build_collaboration_editing.js";
import type * as build_collaboration_export_acl from "../build_collaboration_export_acl.js";
import type * as build_collaboration_export_archive from "../build_collaboration_export_archive.js";
import type * as build_collaboration_export_plan from "../build_collaboration_export_plan.js";
import type * as build_collaboration_exports from "../build_collaboration_exports.js";
import type * as build_collaboration_focus from "../build_collaboration_focus.js";
import type * as build_collaboration_hash from "../build_collaboration_hash.js";
import type * as build_collaboration_human from "../build_collaboration_human.js";
import type * as build_collaboration_inbox from "../build_collaboration_inbox.js";
import type * as build_collaboration_legacy_note_import from "../build_collaboration_legacy_note_import.js";
import type * as build_collaboration_legacy_note_parity from "../build_collaboration_legacy_note_parity.js";
import type * as build_collaboration_legacy_note_plan from "../build_collaboration_legacy_note_plan.js";
import type * as build_collaboration_legacy_note_shared from "../build_collaboration_legacy_note_shared.js";
import type * as build_collaboration_lifecycle from "../build_collaboration_lifecycle.js";
import type * as build_collaboration_lifecycle_state from "../build_collaboration_lifecycle_state.js";
import type * as build_collaboration_links from "../build_collaboration_links.js";
import type * as build_collaboration_migrations from "../build_collaboration_migrations.js";
import type * as build_collaboration_model from "../build_collaboration_model.js";
import type * as build_collaboration_moderation from "../build_collaboration_moderation.js";
import type * as build_collaboration_moderation_helpers from "../build_collaboration_moderation/helpers.js";
import type * as build_collaboration_notifications from "../build_collaboration_notifications.js";
import type * as build_collaboration_pin_migration from "../build_collaboration_pin_migration.js";
import type * as build_collaboration_planning_reconciliation from "../build_collaboration_planning_reconciliation.js";
import type * as build_collaboration_planning_reconciliation_core from "../build_collaboration_planning_reconciliation/core.js";
import type * as build_collaboration_planning_reconciliation_revision from "../build_collaboration_planning_reconciliation/revision.js";
import type * as build_collaboration_planning_reconciliation_viewer from "../build_collaboration_planning_reconciliation/viewer.js";
import type * as build_collaboration_projection from "../build_collaboration_projection.js";
import type * as build_collaboration_projection_helpers from "../build_collaboration_projection/helpers.js";
import type * as build_collaboration_publication_bundle from "../build_collaboration_publication_bundle.js";
import type * as build_collaboration_publication_lifecycle from "../build_collaboration_publication_lifecycle.js";
import type * as build_collaboration_publication_preconditions from "../build_collaboration_publication_preconditions.js";
import type * as build_collaboration_push from "../build_collaboration_push.js";
import type * as build_collaboration_push_maintenance from "../build_collaboration_push_maintenance.js";
import type * as build_collaboration_recipient_access from "../build_collaboration_recipient_access.js";
import type * as build_collaboration_references from "../build_collaboration_references.js";
import type * as build_collaboration_resolution from "../build_collaboration_resolution.js";
import type * as build_collaboration_resolution_helpers from "../build_collaboration_resolution/helpers.js";
import type * as build_collaboration_resolution_migration from "../build_collaboration_resolution_migration.js";
import type * as build_collaboration_retention from "../build_collaboration_retention.js";
import type * as build_collaboration_retention_helpers from "../build_collaboration_retention/helpers.js";
import type * as build_collaboration_rollout from "../build_collaboration_rollout.js";
import type * as build_collaboration_scheduling from "../build_collaboration_scheduling.js";
import type * as build_collaboration_scheduling_helpers from "../build_collaboration_scheduling/helpers.js";
import type * as build_collaboration_scheduling_errors from "../build_collaboration_scheduling_errors.js";
import type * as build_collaboration_search from "../build_collaboration_search.js";
import type * as build_collaboration_search_assets from "../build_collaboration_search/assets.js";
import type * as build_collaboration_search_candidates from "../build_collaboration_search/candidates.js";
import type * as build_collaboration_search_contracts from "../build_collaboration_search/contracts.js";
import type * as build_collaboration_search_ranking from "../build_collaboration_search/ranking.js";
import type * as build_collaboration_search_ranking_constants from "../build_collaboration_search/ranking_constants.js";
import type * as build_collaboration_search_authority_model from "../build_collaboration_search_authority_model.js";
import type * as build_collaboration_search_authority_projection from "../build_collaboration_search_authority_projection.js";
import type * as build_collaboration_search_index from "../build_collaboration_search_index.js";
import type * as build_collaboration_search_maintenance from "../build_collaboration_search_maintenance.js";
import type * as build_collaboration_search_maintenance_helpers from "../build_collaboration_search_maintenance/helpers.js";
import type * as build_collaboration_search_migrations from "../build_collaboration_search_migrations.js";
import type * as build_collaboration_search_reader_sources from "../build_collaboration_search_reader_sources.js";
import type * as build_collaboration_search_readers from "../build_collaboration_search_readers.js";
import type * as build_collaboration_shared_effects from "../build_collaboration_shared_effects.js";
import type * as build_collaboration_system_event_access from "../build_collaboration_system_event_access.js";
import type * as build_collaboration_system_events from "../build_collaboration_system_events.js";
import type * as build_collaboration_system_events_helpers from "../build_collaboration_system_events/helpers.js";
import type * as build_collaboration_system_post_backfill from "../build_collaboration_system_post_backfill.js";
import type * as build_collaboration_system_post_boundary_migrations from "../build_collaboration_system_post_boundary_migrations.js";
import type * as build_collaboration_system_posts from "../build_collaboration_system_posts.js";
import type * as build_collaboration_system_posts_action_items from "../build_collaboration_system_posts/action_items.js";
import type * as build_collaboration_system_posts_activation from "../build_collaboration_system_posts/activation.js";
import type * as build_collaboration_system_posts_lifecycle from "../build_collaboration_system_posts/lifecycle.js";
import type * as build_collaboration_system_posts_presentation from "../build_collaboration_system_posts/presentation.js";
import type * as build_collaboration_threads from "../build_collaboration_threads.js";
import type * as build_collaboration_threads_projection from "../build_collaboration_threads/projection.js";
import type * as build_collaboration_validation from "../build_collaboration_validation.js";
import type * as build_collaboration_validators from "../build_collaboration_validators.js";
import type * as build_collaboration_viewer from "../build_collaboration_viewer.js";
import type * as build_collaboration_webhook_contracts from "../build_collaboration_webhook_contracts.js";
import type * as build_collaboration_webhook_network from "../build_collaboration_webhook_network.js";
import type * as build_collaboration_webhook_signing from "../build_collaboration_webhook_signing.js";
import type * as build_collaboration_webhook_transport from "../build_collaboration_webhook_transport.js";
import type * as build_collaboration_webhooks from "../build_collaboration_webhooks.js";
import type * as build_collaboration_webhooks_helpers from "../build_collaboration_webhooks/helpers.js";
import type * as build_collaboration_workflow_events from "../build_collaboration_workflow_events.js";
import type * as build_draw_coordination from "../build_draw_coordination.js";
import type * as build_operational_idempotency from "../build_operational_idempotency.js";
import type * as build_participant_activation from "../build_participant_activation.js";
import type * as build_participant_revocation from "../build_participant_revocation.js";
import type * as build_participant_revocation_notifications from "../build_participant_revocation_notifications.js";
import type * as build_participants from "../build_participants.js";
import type * as build_submilestone_companion_cutover from "../build_submilestone_companion_cutover.js";
import type * as build_submilestone_companion_cutover_helpers from "../build_submilestone_companion_cutover/helpers.js";
import type * as build_submilestone_companion_cutover_helpers_operational from "../build_submilestone_companion_cutover/helpers/operational.js";
import type * as build_submilestone_companion_cutover_helpers_projection from "../build_submilestone_companion_cutover/helpers/projection.js";
import type * as build_submilestone_evidence from "../build_submilestone_evidence.js";
import type * as build_submilestone_operate_authority from "../build_submilestone_operate_authority.js";
import type * as build_submilestone_review from "../build_submilestone_review.js";
import type * as build_submilestone_review_helpers from "../build_submilestone_review/helpers.js";
import type * as build_submilestone_review_validators from "../build_submilestone_review/validators.js";
import type * as build_submilestone_workspace from "../build_submilestone_workspace.js";
import type * as build_submilestone_workspace_bootstrap from "../build_submilestone_workspace/bootstrap.js";
import type * as build_submilestone_workspace_capabilities from "../build_submilestone_workspace/capabilities.js";
import type * as build_submilestone_workspace_collections from "../build_submilestone_workspace/collections.js";
import type * as build_submilestone_workspace_context from "../build_submilestone_workspace/context.js";
import type * as build_submilestone_workspace_types from "../build_submilestone_workspace/types.js";
import type * as builderRoster from "../builderRoster.js";
import type * as builderRoster_unprovisioned from "../builderRoster/unprovisioned.js";
import type * as builderStaffIdentity from "../builderStaffIdentity.js";
import type * as contractorAuth from "../contractorAuth.js";
import type * as contractorEvidence from "../contractorEvidence.js";
import type * as contractorEvidence_access from "../contractorEvidence/access.js";
import type * as contractorEvidence_evidence from "../contractorEvidence/evidence.js";
import type * as contractorEvidence_handoffs from "../contractorEvidence/handoffs.js";
import type * as contractorEvidence_notifications from "../contractorEvidence/notifications.js";
import type * as contractorEvidence_scope_issues from "../contractorEvidence/scope_issues.js";
import type * as contractorMerge from "../contractorMerge.js";
import type * as contractorOnboarding from "../contractorOnboarding.js";
import type * as contractorOnboarding_access from "../contractorOnboarding/access.js";
import type * as contractorOnboarding_claims from "../contractorOnboarding/claims.js";
import type * as contractorOnboarding_invites from "../contractorOnboarding/invites.js";
import type * as contractorOnboarding_workflow from "../contractorOnboarding/workflow.js";
import type * as contractorWorkspace from "../contractorWorkspace.js";
import type * as contractorWorkspace_access from "../contractorWorkspace/access.js";
import type * as contractorWorkspace_profile from "../contractorWorkspace/profile.js";
import type * as contractorWorkspace_schedule from "../contractorWorkspace/schedule.js";
import type * as contractorWorkspace_work_items from "../contractorWorkspace/work_items.js";
import type * as contractor_identity_scope from "../contractor_identity_scope.js";
import type * as contractor_profile_application from "../contractor_profile_application.js";
import type * as cost_document_access from "../cost_document_access.js";
import type * as cost_document_access_contracts from "../cost_document_access/contracts.js";
import type * as cost_document_access_drafts from "../cost_document_access/drafts.js";
import type * as cost_document_access_policy from "../cost_document_access/policy.js";
import type * as cost_document_access_scope from "../cost_document_access/scope.js";
import type * as cost_document_working_state from "../cost_document_working_state.js";
import type * as cost_documents from "../cost_documents.js";
import type * as cost_documents_audit from "../cost_documents/audit.js";
import type * as cost_documents_contracts from "../cost_documents/contracts.js";
import type * as cost_documents_corrections_integrity from "../cost_documents/corrections_integrity.js";
import type * as cost_documents_draft_mutations from "../cost_documents/draft_mutations.js";
import type * as cost_documents_draft_queries from "../cost_documents/draft_queries.js";
import type * as cost_documents_draft_state from "../cost_documents/draft_state.js";
import type * as cost_documents_projections from "../cost_documents/projections.js";
import type * as cost_documents_review from "../cost_documents/review.js";
import type * as cost_documents_submission from "../cost_documents/submission.js";
import type * as cost_documents_submission_support from "../cost_documents/submission_support.js";
import type * as cost_documents_submitted from "../cost_documents/submitted.js";
import type * as cost_documents_vendor from "../cost_documents/vendor.js";
import type * as crons from "../crons.js";
import type * as data_retention from "../data_retention.js";
import type * as data_retention_access from "../data_retention/access.js";
import type * as data_retention_backup from "../data_retention/backup.js";
import type * as data_retention_contracts from "../data_retention/contracts.js";
import type * as data_retention_fanout from "../data_retention/fanout.js";
import type * as data_retention_maintenance from "../data_retention/maintenance.js";
import type * as data_retention_operations from "../data_retention/operations.js";
import type * as data_retention_policy from "../data_retention/policy.js";
import type * as data_retention_reconciliation from "../data_retention/reconciliation.js";
import type * as data_retention_restore from "../data_retention/restore.js";
import type * as data_retention_schedule from "../data_retention/schedule.js";
import type * as data_retention_support from "../data_retention/support.js";
import type * as data_retention_sweeps from "../data_retention/sweeps.js";
import type * as demo_build_address from "../demo_build_address.js";
import type * as demo_builder_proposals from "../demo_builder_proposals.js";
import type * as demo_builder_proposals_boundary from "../demo_builder_proposals/boundary.js";
import type * as demo_builder_proposals_dashboard from "../demo_builder_proposals/dashboard.js";
import type * as demo_builder_proposals_milestones from "../demo_builder_proposals/milestones.js";
import type * as demo_builder_proposals_projections from "../demo_builder_proposals/projections.js";
import type * as demo_builder_proposals_seed from "../demo_builder_proposals/seed.js";
import type * as demo_builder_proposals_shared from "../demo_builder_proposals/shared.js";
import type * as demo_drawflow from "../demo_drawflow.js";
import type * as demo_drawflow_access from "../demo_drawflow/access.js";
import type * as demo_drawflow_bootstrap from "../demo_drawflow/bootstrap.js";
import type * as demo_drawflow_completion from "../demo_drawflow/completion.js";
import type * as demo_drawflow_dashboard from "../demo_drawflow/dashboard.js";
import type * as demo_drawflow_data from "../demo_drawflow/data.js";
import type * as demo_drawflow_evidence from "../demo_drawflow/evidence.js";
import type * as demo_drawflow_issues from "../demo_drawflow/issues.js";
import type * as demo_drawflow_lifecycle from "../demo_drawflow/lifecycle.js";
import type * as demo_drawflow_milestones from "../demo_drawflow/milestones.js";
import type * as demo_drawflow_projection from "../demo_drawflow/projection.js";
import type * as demo_drawflow_proposal from "../demo_drawflow/proposal.js";
import type * as demo_drawflow_seed from "../demo_drawflow/seed.js";
import type * as demo_drawflow_site_visits from "../demo_drawflow/site_visits.js";
import type * as demo_drawflow_submission from "../demo_drawflow/submission.js";
import type * as demo_drawflow_validation from "../demo_drawflow/validation.js";
import type * as demo_drawflow_workspace from "../demo_drawflow/workspace.js";
import type * as demo_drawflow_backoffice from "../demo_drawflow_backoffice.js";
import type * as demo_drawflow_backoffice_build_mutations from "../demo_drawflow_backoffice/build_mutations.js";
import type * as demo_drawflow_backoffice_contractors from "../demo_drawflow_backoffice/contractors.js";
import type * as demo_drawflow_backoffice_draw from "../demo_drawflow_backoffice/draw.js";
import type * as demo_drawflow_backoffice_notes from "../demo_drawflow_backoffice/notes.js";
import type * as demo_drawflow_backoffice_resolver from "../demo_drawflow_backoffice/resolver.js";
import type * as demo_drawflow_backoffice_seed from "../demo_drawflow_backoffice/seed.js";
import type * as demo_drawflow_backoffice_view from "../demo_drawflow_backoffice/view.js";
import type * as demo_personas from "../demo_personas.js";
import type * as demo_settings from "../demo_settings.js";
import type * as demo_settings_core from "../demo_settings/core.js";
import type * as demo_settings_handlers from "../demo_settings/handlers.js";
import type * as demo_settings_shared from "../demo_settings/shared.js";
import type * as demo_settings_storage from "../demo_settings/storage.js";
import type * as demo_settings_validation from "../demo_settings/validation.js";
import type * as demo_site_visit_guidance from "../demo_site_visit_guidance.js";
import type * as demo_site_visit_tokens from "../demo_site_visit_tokens.js";
import type * as demo_timeline_plans from "../demo_timeline_plans.js";
import type * as demo_timeline_plans_access from "../demo_timeline_plans/access.js";
import type * as demo_timeline_plans_admin from "../demo_timeline_plans/admin.js";
import type * as demo_timeline_plans_backoffice from "../demo_timeline_plans/backoffice.js";
import type * as demo_timeline_plans_capital from "../demo_timeline_plans/capital.js";
import type * as demo_timeline_plans_core from "../demo_timeline_plans/core.js";
import type * as demo_timeline_plans_draws from "../demo_timeline_plans/draws.js";
import type * as demo_timeline_plans_evidence from "../demo_timeline_plans/evidence.js";
import type * as demo_timeline_plans_milestones from "../demo_timeline_plans/milestones.js";
import type * as demo_timeline_plans_plan from "../demo_timeline_plans/plan.js";
import type * as demo_timeline_plans_shared from "../demo_timeline_plans/shared.js";
import type * as demo_timeline_plans_workspace from "../demo_timeline_plans/workspace.js";
import type * as demo_timeline_snapshots from "../demo_timeline_snapshots.js";
import type * as email_transport from "../email_transport.js";
import type * as evidence_preview from "../evidence_preview.js";
import type * as fairLendConfig from "../fairLendConfig.js";
import type * as fluent from "../fluent.js";
import type * as gardenSuiteTemplate from "../gardenSuiteTemplate.js";
import type * as http from "../http.js";
import type * as identity_invitation_emails from "../identity_invitation_emails.js";
import type * as lenderOrganizationAccess from "../lenderOrganizationAccess.js";
import type * as lenderOrganizationReviewPolicies from "../lenderOrganizationReviewPolicies.js";
import type * as lenderOrganizations from "../lenderOrganizations.js";
import type * as lender_assignment_manifest from "../lender_assignment_manifest.js";
import type * as lender_organizations_contracts from "../lender_organizations/contracts.js";
import type * as lender_organizations_helpers from "../lender_organizations/helpers.js";
import type * as lender_organizations_member_deactivation from "../lender_organizations/member_deactivation.js";
import type * as lender_portal from "../lender_portal.js";
import type * as lender_portal_build_detail from "../lender_portal/build_detail.js";
import type * as lender_portal_collaboration from "../lender_portal/collaboration.js";
import type * as lender_portal_collaboration_access from "../lender_portal/collaboration_access.js";
import type * as lender_portal_collaboration_asset_actions from "../lender_portal/collaboration_asset_actions.js";
import type * as lender_portal_collaboration_assets from "../lender_portal/collaboration_assets.js";
import type * as lender_portal_dashboard from "../lender_portal/dashboard.js";
import type * as lender_portal_draw_queue from "../lender_portal/draw_queue.js";
import type * as lender_portal_proposals from "../lender_portal/proposals.js";
import type * as lender_portal_shared from "../lender_portal/shared.js";
import type * as lender_portal_access from "../lender_portal_access.js";
import type * as lender_portal_notifications from "../lender_portal_notifications.js";
import type * as lender_portal_notifications_contracts from "../lender_portal_notifications/contracts.js";
import type * as lender_portal_notifications_enqueue from "../lender_portal_notifications/enqueue.js";
import type * as lender_portal_notifications_shared from "../lender_portal_notifications/shared.js";
import type * as lender_portal_notifications_suppression from "../lender_portal_notifications/suppression.js";
import type * as lender_portal_pagination from "../lender_portal_pagination.js";
import type * as lender_portal_phase3 from "../lender_portal_phase3.js";
import type * as lender_portal_phase4 from "../lender_portal_phase4.js";
import type * as lender_portal_phase5 from "../lender_portal_phase5.js";
import type * as lender_portal_phase5_evidence from "../lender_portal_phase5/evidence.js";
import type * as lender_portal_phase5_lifecycle from "../lender_portal_phase5/lifecycle.js";
import type * as lender_portal_phase5_projections from "../lender_portal_phase5/projections.js";
import type * as lender_portal_phase5_shared from "../lender_portal_phase5/shared.js";
import type * as lender_portal_phase5_site_visits from "../lender_portal_phase5/site_visits.js";
import type * as lender_portal_phase5_contracts from "../lender_portal_phase5_contracts.js";
import type * as lender_portal_phase9 from "../lender_portal_phase9.js";
import type * as lender_portal_phase9_inventory from "../lender_portal_phase9/inventory.js";
import type * as lender_portal_phase9_runs from "../lender_portal_phase9/runs.js";
import type * as lender_portal_phase9_shared from "../lender_portal_phase9/shared.js";
import type * as lender_portal_phase9_snapshot from "../lender_portal_phase9/snapshot.js";
import type * as lender_portal_phase9_snapshot_support from "../lender_portal_phase9/snapshot_support.js";
import type * as lender_portal_phase9_contracts from "../lender_portal_phase9_contracts.js";
import type * as lender_portal_release from "../lender_portal_release.js";
import type * as lender_portal_release_helpers from "../lender_portal_release/helpers.js";
import type * as migrations from "../migrations.js";
import type * as migrations_context from "../migrations/context.js";
import type * as migrations_legacy from "../migrations/legacy.js";
import type * as migrations_lender_member_permissions from "../migrations/lender_member_permissions.js";
import type * as migrations_lender_organization from "../migrations/lender_organization.js";
import type * as migrations_phase3 from "../migrations/phase3.js";
import type * as migrations_phase9 from "../migrations/phase9.js";
import type * as milestone_start from "../milestone_start.js";
import type * as production_proposal_detail from "../production_proposal_detail.js";
import type * as production_proposal_lifecycle from "../production_proposal_lifecycle.js";
import type * as production_proposals from "../production_proposals.js";
import type * as production_proposals_active_build_completion from "../production_proposals/active_build_completion.js";
import type * as production_proposals_active_build_contractors from "../production_proposals/active_build_contractors.js";
import type * as production_proposals_active_build_detail from "../production_proposals/active_build_detail.js";
import type * as production_proposals_active_build_documents from "../production_proposals/active_build_documents.js";
import type * as production_proposals_active_build_draw_migration from "../production_proposals/active_build_draw_migration.js";
import type * as production_proposals_active_build_draws from "../production_proposals/active_build_draws.js";
import type * as production_proposals_active_build_evidence_storage from "../production_proposals/active_build_evidence_storage.js";
import type * as production_proposals_active_build_planning from "../production_proposals/active_build_planning.js";
import type * as production_proposals_active_build_profile from "../production_proposals/active_build_profile.js";
import type * as production_proposals_active_build_projection from "../production_proposals/active_build_projection.js";
import type * as production_proposals_active_build_reviews from "../production_proposals/active_build_reviews.js";
import type * as production_proposals_active_build_site_visits from "../production_proposals/active_build_site_visits.js";
import type * as production_proposals_active_build_staff from "../production_proposals/active_build_staff.js";
import type * as production_proposals_active_build_submilestone_evidence from "../production_proposals/active_build_submilestone_evidence.js";
import type * as production_proposals_active_build_submilestone_execution from "../production_proposals/active_build_submilestone_execution.js";
import type * as production_proposals_active_build_timeline from "../production_proposals/active_build_timeline.js";
import type * as production_proposals_active_capital_evidence from "../production_proposals/active_capital_evidence.js";
import type * as production_proposals_active_cost from "../production_proposals/active_cost.js";
import type * as production_proposals_active_funding from "../production_proposals/active_funding.js";
import type * as production_proposals_active_planning from "../production_proposals/active_planning.js";
import type * as production_proposals_assignment_manifest from "../production_proposals/assignment_manifest.js";
import type * as production_proposals_audit_helpers from "../production_proposals/audit_helpers.js";
import type * as production_proposals_authorization_core from "../production_proposals/authorization_core.js";
import type * as production_proposals_backoffice_proposal_views from "../production_proposals/backoffice_proposal_views.js";
import type * as production_proposals_brokerage_draws from "../production_proposals/brokerage_draws.js";
import type * as production_proposals_brokerage_site_visits from "../production_proposals/brokerage_site_visits.js";
import type * as production_proposals_builder_onboarding from "../production_proposals/builder_onboarding.js";
import type * as production_proposals_builder_staff_access from "../production_proposals/builder_staff_access.js";
import type * as production_proposals_builder_staff_persistence from "../production_proposals/builder_staff_persistence.js";
import type * as production_proposals_calendar_contracts from "../production_proposals/calendar_contracts.js";
import type * as production_proposals_calendar_scheduling from "../production_proposals/calendar_scheduling.js";
import type * as production_proposals_calendar_workspaces from "../production_proposals/calendar_workspaces.js";
import type * as production_proposals_confirmation_history_helpers from "../production_proposals/confirmation_history_helpers.js";
import type * as production_proposals_contractor_active_helpers from "../production_proposals/contractor_active_helpers.js";
import type * as production_proposals_contractor_assignments from "../production_proposals/contractor_assignments.js";
import type * as production_proposals_contractor_policy_helpers from "../production_proposals/contractor_policy_helpers.js";
import type * as production_proposals_contractor_profiles from "../production_proposals/contractor_profiles.js";
import type * as production_proposals_contractor_proposal_helpers from "../production_proposals/contractor_proposal_helpers.js";
import type * as production_proposals_contractor_relationship_helpers from "../production_proposals/contractor_relationship_helpers.js";
import type * as production_proposals_contracts_foundation from "../production_proposals/contracts_foundation.js";
import type * as production_proposals_contracts_workflow from "../production_proposals/contracts_workflow.js";
import type * as production_proposals_directory_cards from "../production_proposals/directory_cards.js";
import type * as production_proposals_integration_helpers from "../production_proposals/integration_helpers.js";
import type * as production_proposals_integrations from "../production_proposals/integrations.js";
import type * as production_proposals_legacy_seed from "../production_proposals/legacy_seed.js";
import type * as production_proposals_lender_assignment_auth from "../production_proposals/lender_assignment_auth.js";
import type * as production_proposals_lender_detail from "../production_proposals/lender_detail.js";
import type * as production_proposals_notification_delivery_helpers from "../production_proposals/notification_delivery_helpers.js";
import type * as production_proposals_operations_handoffs from "../production_proposals/operations_handoffs.js";
import type * as production_proposals_operations_helpers from "../production_proposals/operations_helpers.js";
import type * as production_proposals_proposal_activation from "../production_proposals/proposal_activation.js";
import type * as production_proposals_proposal_assignment_admin from "../production_proposals/proposal_assignment_admin.js";
import type * as production_proposals_proposal_assignments from "../production_proposals/proposal_assignments.js";
import type * as production_proposals_proposal_build_cost from "../production_proposals/proposal_build_cost.js";
import type * as production_proposals_proposal_capital from "../production_proposals/proposal_capital.js";
import type * as production_proposals_proposal_claim from "../production_proposals/proposal_claim.js";
import type * as production_proposals_proposal_confirmation from "../production_proposals/proposal_confirmation.js";
import type * as production_proposals_proposal_copy_audit from "../production_proposals/proposal_copy_audit.js";
import type * as production_proposals_proposal_cost_persistence from "../production_proposals/proposal_cost_persistence.js";
import type * as production_proposals_proposal_cost_validation from "../production_proposals/proposal_cost_validation.js";
import type * as production_proposals_proposal_detail_projection from "../production_proposals/proposal_detail_projection.js";
import type * as production_proposals_proposal_draft_model from "../production_proposals/proposal_draft_model.js";
import type * as production_proposals_proposal_draft_persistence from "../production_proposals/proposal_draft_persistence.js";
import type * as production_proposals_proposal_draw_plan from "../production_proposals/proposal_draw_plan.js";
import type * as production_proposals_proposal_evidence_completion from "../production_proposals/proposal_evidence_completion.js";
import type * as production_proposals_proposal_lender_approval from "../production_proposals/proposal_lender_approval.js";
import type * as production_proposals_proposal_review_commands from "../production_proposals/proposal_review_commands.js";
import type * as production_proposals_proposal_review_reads from "../production_proposals/proposal_review_reads.js";
import type * as production_proposals_proposal_review_restore from "../production_proposals/proposal_review_restore.js";
import type * as production_proposals_proposal_revision_commands from "../production_proposals/proposal_revision_commands.js";
import type * as production_proposals_proposal_seed from "../production_proposals/proposal_seed.js";
import type * as production_proposals_proposal_settings from "../production_proposals/proposal_settings.js";
import type * as production_proposals_proposal_timeline from "../production_proposals/proposal_timeline.js";
import type * as production_proposals_proposal_timeline_workspace from "../production_proposals/proposal_timeline_workspace.js";
import type * as production_proposals_review_lifecycle_helpers from "../production_proposals/review_lifecycle_helpers.js";
import type * as production_proposals_roster_contracts from "../production_proposals/roster_contracts.js";
import type * as production_proposals_roster_projection_helpers from "../production_proposals/roster_projection_helpers.js";
import type * as production_proposals_roster_queries from "../production_proposals/roster_queries.js";
import type * as production_proposals_roster_views from "../production_proposals/roster_views.js";
import type * as production_proposals_seed_default_builders from "../production_proposals/seed_default_builders.js";
import type * as production_proposals_seed_foundation from "../production_proposals/seed_foundation.js";
import type * as production_proposals_seed_scenario from "../production_proposals/seed_scenario.js";
import type * as production_proposals_seed_template_defaults from "../production_proposals/seed_template_defaults.js";
import type * as production_proposals_seed_template_writer from "../production_proposals/seed_template_writer.js";
import type * as production_proposals_settings_helpers from "../production_proposals/settings_helpers.js";
import type * as production_proposals_site_visit_calendar from "../production_proposals/site_visit_calendar.js";
import type * as production_proposals_site_visit_helpers from "../production_proposals/site_visit_helpers.js";
import type * as production_proposals_storage_helpers from "../production_proposals/storage_helpers.js";
import type * as production_proposals_submilestone_commands from "../production_proposals/submilestone_commands.js";
import type * as proposal_collaboration from "../proposal_collaboration.js";
import type * as proposal_collaboration_audit from "../proposal_collaboration/audit.js";
import type * as proposal_collaboration_authorization from "../proposal_collaboration/authorization.js";
import type * as proposal_collaboration_context from "../proposal_collaboration/context.js";
import type * as proposal_collaboration_contracts from "../proposal_collaboration/contracts.js";
import type * as proposal_collaboration_identity from "../proposal_collaboration/identity.js";
import type * as proposal_collaboration_presence from "../proposal_collaboration/presence.js";
import type * as proposal_collaboration_snapshots from "../proposal_collaboration/snapshots.js";
import type * as proposal_collaboration_model from "../proposal_collaboration_model.js";
import type * as proposal_revision_lender_snapshot from "../proposal_revision_lender_snapshot.js";
import type * as qaIdentityCleanup from "../qaIdentityCleanup.js";
import type * as qaIdentityCleanupTables from "../qaIdentityCleanupTables.js";
import type * as quote_authoring_access from "../quote_authoring_access.js";
import type * as quote_comparisons from "../quote_comparisons.js";
import type * as quote_comparisons_access from "../quote_comparisons/access.js";
import type * as quote_comparisons_candidates from "../quote_comparisons/candidates.js";
import type * as quote_comparisons_contract from "../quote_comparisons/contract.js";
import type * as quote_comparisons_read from "../quote_comparisons/read.js";
import type * as quote_invitation_access from "../quote_invitation_access.js";
import type * as quote_invitation_access_core from "../quote_invitation_access/core.js";
import type * as quote_invitation_access_handlers from "../quote_invitation_access/handlers.js";
import type * as quote_invitation_access_projection from "../quote_invitation_access/projection.js";
import type * as quote_invitation_access_recipient from "../quote_invitation_access/recipient.js";
import type * as quote_notifications from "../quote_notifications.js";
import type * as quote_notifications_contracts from "../quote_notifications/contracts.js";
import type * as quote_notifications_delivery from "../quote_notifications/delivery.js";
import type * as quote_notifications_email from "../quote_notifications/email.js";
import type * as quote_notifications_projection from "../quote_notifications/projection.js";
import type * as quote_notifications_scheduling from "../quote_notifications/scheduling.js";
import type * as quote_preferred from "../quote_preferred.js";
import type * as quote_response_drafts from "../quote_response_drafts.js";
import type * as quote_response_drafts_attachments from "../quote_response_drafts/attachments.js";
import type * as quote_response_drafts_core from "../quote_response_drafts/core.js";
import type * as quote_response_drafts_migration from "../quote_response_drafts/migration.js";
import type * as quote_response_drafts_mutations from "../quote_response_drafts/mutations.js";
import type * as quote_response_drafts_read_write from "../quote_response_drafts/read_write.js";
import type * as quote_response_submissions from "../quote_response_submissions.js";
import type * as quote_response_submissions_core from "../quote_response_submissions/core.js";
import type * as quote_response_submissions_mutations from "../quote_response_submissions/mutations.js";
import type * as quote_response_submissions_projection from "../quote_response_submissions/projection.js";
import type * as quote_response_submissions_read from "../quote_response_submissions/read.js";
import type * as quote_response_submissions_validation from "../quote_response_submissions/validation.js";
import type * as quote_response_template_migrations from "../quote_response_template_migrations.js";
import type * as quote_response_templates from "../quote_response_templates.js";
import type * as quote_response_templates_core from "../quote_response_templates/core.js";
import type * as quote_response_templates_handlers from "../quote_response_templates/handlers.js";
import type * as quote_round_lifecycle from "../quote_round_lifecycle.js";
import type * as quote_round_lifecycle_core from "../quote_round_lifecycle/core.js";
import type * as quote_round_lifecycle_invitation_handlers from "../quote_round_lifecycle/invitation_handlers.js";
import type * as quote_round_lifecycle_round_handlers from "../quote_round_lifecycle/round_handlers.js";
import type * as quote_rounds from "../quote_rounds.js";
import type * as quote_rounds_access from "../quote_rounds/access.js";
import type * as quote_rounds_composer from "../quote_rounds/composer.js";
import type * as quote_rounds_contracts from "../quote_rounds/contracts.js";
import type * as quote_rounds_draft_mutations from "../quote_rounds/draft_mutations.js";
import type * as quote_rounds_draft_validation from "../quote_rounds/draft_validation.js";
import type * as quote_rounds_list from "../quote_rounds/list.js";
import type * as quote_rounds_mutations from "../quote_rounds/mutations.js";
import type * as quote_rounds_projections from "../quote_rounds/projections.js";
import type * as quote_rounds_publication from "../quote_rounds/publication.js";
import type * as quote_rounds_publication_validation from "../quote_rounds/publication_validation.js";
import type * as recipient_delivery_projection from "../recipient_delivery_projection.js";
import type * as schema_build_collaboration_01 from "../schema/build_collaboration_01.js";
import type * as schema_build_collaboration_02 from "../schema/build_collaboration_02.js";
import type * as schema_build_collaboration_03 from "../schema/build_collaboration_03.js";
import type * as schema_build_collaboration_04 from "../schema/build_collaboration_04.js";
import type * as schema_build_workspace_01 from "../schema/build_workspace_01.js";
import type * as schema_build_workspace_02 from "../schema/build_workspace_02.js";
import type * as schema_build_workspace_03 from "../schema/build_workspace_03.js";
import type * as schema_communications_01 from "../schema/communications_01.js";
import type * as schema_core_01 from "../schema/core_01.js";
import type * as schema_demo_01 from "../schema/demo_01.js";
import type * as schema_demo_02 from "../schema/demo_02.js";
import type * as schema_identity_01 from "../schema/identity_01.js";
import type * as schema_proposal_lifecycle_01 from "../schema/proposal_lifecycle_01.js";
import type * as schema_proposal_lifecycle_02 from "../schema/proposal_lifecycle_02.js";
import type * as schema_quoting_01 from "../schema/quoting_01.js";
import type * as schema_quoting_02 from "../schema/quoting_02.js";
import type * as schema_retention_01 from "../schema/retention_01.js";
import type * as schema_review_policy_defaults_01 from "../schema/review_policy_defaults_01.js";
import type * as schema_scheduling_01 from "../schema/scheduling_01.js";
import type * as schema_validators from "../schema/validators.js";
import type * as siteVisitGuidance from "../siteVisitGuidance.js";
import type * as submilestone_field_guidance from "../submilestone_field_guidance.js";
import type * as submilestone_scope_contracts from "../submilestone_scope_contracts.js";
import type * as submilestone_scope_contracts_decisions from "../submilestone_scope_contracts/decisions.js";
import type * as submilestone_scope_contracts_revisions from "../submilestone_scope_contracts/revisions.js";
import type * as submilestone_scope_contracts_shared from "../submilestone_scope_contracts/shared.js";
import type * as submilestone_scope_guidance_migrations from "../submilestone_scope_guidance_migrations.js";
import type * as todos from "../todos.js";
import type * as types from "../types.js";
import type * as workosManagement from "../workosManagement.js";
import type * as workosManagement_context from "../workosManagement/context.js";
import type * as workosManagement_directory from "../workosManagement/directory.js";
import type * as workosManagement_invitationEmails from "../workosManagement/invitationEmails.js";
import type * as workosManagement_membership from "../workosManagement/membership.js";
import type * as workosManagement_shared from "../workosManagement/shared.js";
import type * as workosManagement_transfer from "../workosManagement/transfer.js";
import type * as workosProjection from "../workosProjection.js";
import type * as workosProjection_events from "../workosProjection/events.js";
import type * as workosProjection_reads from "../workosProjection/reads.js";
import type * as workos_permission_access from "../workos_permission_access.js";

import type {
  ApiFromModules,
  FilterApi,
  FunctionReference,
} from "convex/server";

declare const fullApi: ApiFromModules<{
  activeBuildAccess: typeof activeBuildAccess;
  active_build_document_lineage: typeof active_build_document_lineage;
  administrative_override_policy: typeof administrative_override_policy;
  assistant: typeof assistant;
  "assistant/access": typeof assistant_access;
  "assistant/action_handlers": typeof assistant_action_handlers;
  "assistant/action_mutations": typeof assistant_action_mutations;
  "assistant/action_preview": typeof assistant_action_preview;
  "assistant/briefing": typeof assistant_briefing;
  "assistant/contracts": typeof assistant_contracts;
  "assistant/inputs": typeof assistant_inputs;
  "assistant/mutations": typeof assistant_mutations;
  "assistant/planning": typeof assistant_planning;
  "assistant/shared": typeof assistant_shared;
  "assistant/tool_definitions": typeof assistant_tool_definitions;
  "assistant/workflow_handlers": typeof assistant_workflow_handlers;
  assistantProvider: typeof assistantProvider;
  audit_event_migrations: typeof audit_event_migrations;
  auth: typeof auth;
  authz: typeof authz;
  authzTest: typeof authzTest;
  brokerAssignments: typeof brokerAssignments;
  brokerageProvisioning: typeof brokerageProvisioning;
  "brokerageProvisioning/provisioning": typeof brokerageProvisioning_provisioning;
  "brokerageProvisioning/relationship": typeof brokerageProvisioning_relationship;
  build_action_item_application: typeof build_action_item_application;
  build_action_item_deadline_migrations: typeof build_action_item_deadline_migrations;
  build_action_item_deadline_model: typeof build_action_item_deadline_model;
  build_action_item_details: typeof build_action_item_details;
  build_action_item_governance: typeof build_action_item_governance;
  build_action_item_history: typeof build_action_item_history;
  build_action_item_post_links: typeof build_action_item_post_links;
  build_action_item_queue_projection: typeof build_action_item_queue_projection;
  build_action_item_queues: typeof build_action_item_queues;
  "build_action_item_queues/helpers": typeof build_action_item_queues_helpers;
  build_action_item_rbac: typeof build_action_item_rbac;
  build_action_item_structure: typeof build_action_item_structure;
  "build_action_item_structure/helpers": typeof build_action_item_structure_helpers;
  build_action_item_structure_model: typeof build_action_item_structure_model;
  build_action_item_tags: typeof build_action_item_tags;
  build_action_item_workflow: typeof build_action_item_workflow;
  "build_action_item_workflow/policy": typeof build_action_item_workflow_policy;
  build_action_items: typeof build_action_items;
  "build_action_items/helpers": typeof build_action_items_helpers;
  build_collaboration: typeof build_collaboration;
  "build_collaboration/helpers": typeof build_collaboration_helpers;
  build_collaboration_access: typeof build_collaboration_access;
  build_collaboration_acknowledgements: typeof build_collaboration_acknowledgements;
  build_collaboration_actor: typeof build_collaboration_actor;
  build_collaboration_archive: typeof build_collaboration_archive;
  "build_collaboration_archive/action_items": typeof build_collaboration_archive_action_items;
  "build_collaboration_archive/common": typeof build_collaboration_archive_common;
  "build_collaboration_archive/contracts": typeof build_collaboration_archive_contracts;
  "build_collaboration_archive/moderation": typeof build_collaboration_archive_moderation;
  "build_collaboration_archive/revision": typeof build_collaboration_archive_revision;
  build_collaboration_asset_access: typeof build_collaboration_asset_access;
  build_collaboration_asset_actions: typeof build_collaboration_asset_actions;
  build_collaboration_asset_maintenance: typeof build_collaboration_asset_maintenance;
  build_collaboration_asset_projection: typeof build_collaboration_asset_projection;
  build_collaboration_asset_publication: typeof build_collaboration_asset_publication;
  build_collaboration_asset_upload_application: typeof build_collaboration_asset_upload_application;
  build_collaboration_assets: typeof build_collaboration_assets;
  "build_collaboration_assets/helpers": typeof build_collaboration_assets_helpers;
  build_collaboration_content: typeof build_collaboration_content;
  build_collaboration_contracts: typeof build_collaboration_contracts;
  build_collaboration_cutover_certification: typeof build_collaboration_cutover_certification;
  build_collaboration_cutover_rehearsals: typeof build_collaboration_cutover_rehearsals;
  build_collaboration_delivery: typeof build_collaboration_delivery;
  build_collaboration_delivery_api: typeof build_collaboration_delivery_api;
  build_collaboration_delivery_maintenance: typeof build_collaboration_delivery_maintenance;
  "build_collaboration_delivery_maintenance/attempts": typeof build_collaboration_delivery_maintenance_attempts;
  "build_collaboration_delivery_maintenance/contracts": typeof build_collaboration_delivery_maintenance_contracts;
  "build_collaboration_delivery_maintenance/helpers": typeof build_collaboration_delivery_maintenance_helpers;
  "build_collaboration_delivery_maintenance/preparation": typeof build_collaboration_delivery_maintenance_preparation;
  build_collaboration_delivery_model: typeof build_collaboration_delivery_model;
  build_collaboration_delivery_reconciliation: typeof build_collaboration_delivery_reconciliation;
  build_collaboration_delivery_transport: typeof build_collaboration_delivery_transport;
  build_collaboration_delivery_transport_provider: typeof build_collaboration_delivery_transport_provider;
  build_collaboration_drafts: typeof build_collaboration_drafts;
  build_collaboration_editing: typeof build_collaboration_editing;
  build_collaboration_export_acl: typeof build_collaboration_export_acl;
  build_collaboration_export_archive: typeof build_collaboration_export_archive;
  build_collaboration_export_plan: typeof build_collaboration_export_plan;
  build_collaboration_exports: typeof build_collaboration_exports;
  build_collaboration_focus: typeof build_collaboration_focus;
  build_collaboration_hash: typeof build_collaboration_hash;
  build_collaboration_human: typeof build_collaboration_human;
  build_collaboration_inbox: typeof build_collaboration_inbox;
  build_collaboration_legacy_note_import: typeof build_collaboration_legacy_note_import;
  build_collaboration_legacy_note_parity: typeof build_collaboration_legacy_note_parity;
  build_collaboration_legacy_note_plan: typeof build_collaboration_legacy_note_plan;
  build_collaboration_legacy_note_shared: typeof build_collaboration_legacy_note_shared;
  build_collaboration_lifecycle: typeof build_collaboration_lifecycle;
  build_collaboration_lifecycle_state: typeof build_collaboration_lifecycle_state;
  build_collaboration_links: typeof build_collaboration_links;
  build_collaboration_migrations: typeof build_collaboration_migrations;
  build_collaboration_model: typeof build_collaboration_model;
  build_collaboration_moderation: typeof build_collaboration_moderation;
  "build_collaboration_moderation/helpers": typeof build_collaboration_moderation_helpers;
  build_collaboration_notifications: typeof build_collaboration_notifications;
  build_collaboration_pin_migration: typeof build_collaboration_pin_migration;
  build_collaboration_planning_reconciliation: typeof build_collaboration_planning_reconciliation;
  "build_collaboration_planning_reconciliation/core": typeof build_collaboration_planning_reconciliation_core;
  "build_collaboration_planning_reconciliation/revision": typeof build_collaboration_planning_reconciliation_revision;
  "build_collaboration_planning_reconciliation/viewer": typeof build_collaboration_planning_reconciliation_viewer;
  build_collaboration_projection: typeof build_collaboration_projection;
  "build_collaboration_projection/helpers": typeof build_collaboration_projection_helpers;
  build_collaboration_publication_bundle: typeof build_collaboration_publication_bundle;
  build_collaboration_publication_lifecycle: typeof build_collaboration_publication_lifecycle;
  build_collaboration_publication_preconditions: typeof build_collaboration_publication_preconditions;
  build_collaboration_push: typeof build_collaboration_push;
  build_collaboration_push_maintenance: typeof build_collaboration_push_maintenance;
  build_collaboration_recipient_access: typeof build_collaboration_recipient_access;
  build_collaboration_references: typeof build_collaboration_references;
  build_collaboration_resolution: typeof build_collaboration_resolution;
  "build_collaboration_resolution/helpers": typeof build_collaboration_resolution_helpers;
  build_collaboration_resolution_migration: typeof build_collaboration_resolution_migration;
  build_collaboration_retention: typeof build_collaboration_retention;
  "build_collaboration_retention/helpers": typeof build_collaboration_retention_helpers;
  build_collaboration_rollout: typeof build_collaboration_rollout;
  build_collaboration_scheduling: typeof build_collaboration_scheduling;
  "build_collaboration_scheduling/helpers": typeof build_collaboration_scheduling_helpers;
  build_collaboration_scheduling_errors: typeof build_collaboration_scheduling_errors;
  build_collaboration_search: typeof build_collaboration_search;
  "build_collaboration_search/assets": typeof build_collaboration_search_assets;
  "build_collaboration_search/candidates": typeof build_collaboration_search_candidates;
  "build_collaboration_search/contracts": typeof build_collaboration_search_contracts;
  "build_collaboration_search/ranking": typeof build_collaboration_search_ranking;
  "build_collaboration_search/ranking_constants": typeof build_collaboration_search_ranking_constants;
  build_collaboration_search_authority_model: typeof build_collaboration_search_authority_model;
  build_collaboration_search_authority_projection: typeof build_collaboration_search_authority_projection;
  build_collaboration_search_index: typeof build_collaboration_search_index;
  build_collaboration_search_maintenance: typeof build_collaboration_search_maintenance;
  "build_collaboration_search_maintenance/helpers": typeof build_collaboration_search_maintenance_helpers;
  build_collaboration_search_migrations: typeof build_collaboration_search_migrations;
  build_collaboration_search_reader_sources: typeof build_collaboration_search_reader_sources;
  build_collaboration_search_readers: typeof build_collaboration_search_readers;
  build_collaboration_shared_effects: typeof build_collaboration_shared_effects;
  build_collaboration_system_event_access: typeof build_collaboration_system_event_access;
  build_collaboration_system_events: typeof build_collaboration_system_events;
  "build_collaboration_system_events/helpers": typeof build_collaboration_system_events_helpers;
  build_collaboration_system_post_backfill: typeof build_collaboration_system_post_backfill;
  build_collaboration_system_post_boundary_migrations: typeof build_collaboration_system_post_boundary_migrations;
  build_collaboration_system_posts: typeof build_collaboration_system_posts;
  "build_collaboration_system_posts/action_items": typeof build_collaboration_system_posts_action_items;
  "build_collaboration_system_posts/activation": typeof build_collaboration_system_posts_activation;
  "build_collaboration_system_posts/lifecycle": typeof build_collaboration_system_posts_lifecycle;
  "build_collaboration_system_posts/presentation": typeof build_collaboration_system_posts_presentation;
  build_collaboration_threads: typeof build_collaboration_threads;
  "build_collaboration_threads/projection": typeof build_collaboration_threads_projection;
  build_collaboration_validation: typeof build_collaboration_validation;
  build_collaboration_validators: typeof build_collaboration_validators;
  build_collaboration_viewer: typeof build_collaboration_viewer;
  build_collaboration_webhook_contracts: typeof build_collaboration_webhook_contracts;
  build_collaboration_webhook_network: typeof build_collaboration_webhook_network;
  build_collaboration_webhook_signing: typeof build_collaboration_webhook_signing;
  build_collaboration_webhook_transport: typeof build_collaboration_webhook_transport;
  build_collaboration_webhooks: typeof build_collaboration_webhooks;
  "build_collaboration_webhooks/helpers": typeof build_collaboration_webhooks_helpers;
  build_collaboration_workflow_events: typeof build_collaboration_workflow_events;
  build_draw_coordination: typeof build_draw_coordination;
  build_operational_idempotency: typeof build_operational_idempotency;
  build_participant_activation: typeof build_participant_activation;
  build_participant_revocation: typeof build_participant_revocation;
  build_participant_revocation_notifications: typeof build_participant_revocation_notifications;
  build_participants: typeof build_participants;
  build_submilestone_companion_cutover: typeof build_submilestone_companion_cutover;
  "build_submilestone_companion_cutover/helpers": typeof build_submilestone_companion_cutover_helpers;
  "build_submilestone_companion_cutover/helpers/operational": typeof build_submilestone_companion_cutover_helpers_operational;
  "build_submilestone_companion_cutover/helpers/projection": typeof build_submilestone_companion_cutover_helpers_projection;
  build_submilestone_evidence: typeof build_submilestone_evidence;
  build_submilestone_operate_authority: typeof build_submilestone_operate_authority;
  build_submilestone_review: typeof build_submilestone_review;
  "build_submilestone_review/helpers": typeof build_submilestone_review_helpers;
  "build_submilestone_review/validators": typeof build_submilestone_review_validators;
  build_submilestone_workspace: typeof build_submilestone_workspace;
  "build_submilestone_workspace/bootstrap": typeof build_submilestone_workspace_bootstrap;
  "build_submilestone_workspace/capabilities": typeof build_submilestone_workspace_capabilities;
  "build_submilestone_workspace/collections": typeof build_submilestone_workspace_collections;
  "build_submilestone_workspace/context": typeof build_submilestone_workspace_context;
  "build_submilestone_workspace/types": typeof build_submilestone_workspace_types;
  builderRoster: typeof builderRoster;
  "builderRoster/unprovisioned": typeof builderRoster_unprovisioned;
  builderStaffIdentity: typeof builderStaffIdentity;
  contractorAuth: typeof contractorAuth;
  contractorEvidence: typeof contractorEvidence;
  "contractorEvidence/access": typeof contractorEvidence_access;
  "contractorEvidence/evidence": typeof contractorEvidence_evidence;
  "contractorEvidence/handoffs": typeof contractorEvidence_handoffs;
  "contractorEvidence/notifications": typeof contractorEvidence_notifications;
  "contractorEvidence/scope_issues": typeof contractorEvidence_scope_issues;
  contractorMerge: typeof contractorMerge;
  contractorOnboarding: typeof contractorOnboarding;
  "contractorOnboarding/access": typeof contractorOnboarding_access;
  "contractorOnboarding/claims": typeof contractorOnboarding_claims;
  "contractorOnboarding/invites": typeof contractorOnboarding_invites;
  "contractorOnboarding/workflow": typeof contractorOnboarding_workflow;
  contractorWorkspace: typeof contractorWorkspace;
  "contractorWorkspace/access": typeof contractorWorkspace_access;
  "contractorWorkspace/profile": typeof contractorWorkspace_profile;
  "contractorWorkspace/schedule": typeof contractorWorkspace_schedule;
  "contractorWorkspace/work_items": typeof contractorWorkspace_work_items;
  contractor_identity_scope: typeof contractor_identity_scope;
  contractor_profile_application: typeof contractor_profile_application;
  cost_document_access: typeof cost_document_access;
  "cost_document_access/contracts": typeof cost_document_access_contracts;
  "cost_document_access/drafts": typeof cost_document_access_drafts;
  "cost_document_access/policy": typeof cost_document_access_policy;
  "cost_document_access/scope": typeof cost_document_access_scope;
  cost_document_working_state: typeof cost_document_working_state;
  cost_documents: typeof cost_documents;
  "cost_documents/audit": typeof cost_documents_audit;
  "cost_documents/contracts": typeof cost_documents_contracts;
  "cost_documents/corrections_integrity": typeof cost_documents_corrections_integrity;
  "cost_documents/draft_mutations": typeof cost_documents_draft_mutations;
  "cost_documents/draft_queries": typeof cost_documents_draft_queries;
  "cost_documents/draft_state": typeof cost_documents_draft_state;
  "cost_documents/projections": typeof cost_documents_projections;
  "cost_documents/review": typeof cost_documents_review;
  "cost_documents/submission": typeof cost_documents_submission;
  "cost_documents/submission_support": typeof cost_documents_submission_support;
  "cost_documents/submitted": typeof cost_documents_submitted;
  "cost_documents/vendor": typeof cost_documents_vendor;
  crons: typeof crons;
  data_retention: typeof data_retention;
  "data_retention/access": typeof data_retention_access;
  "data_retention/backup": typeof data_retention_backup;
  "data_retention/contracts": typeof data_retention_contracts;
  "data_retention/fanout": typeof data_retention_fanout;
  "data_retention/maintenance": typeof data_retention_maintenance;
  "data_retention/operations": typeof data_retention_operations;
  "data_retention/policy": typeof data_retention_policy;
  "data_retention/reconciliation": typeof data_retention_reconciliation;
  "data_retention/restore": typeof data_retention_restore;
  "data_retention/schedule": typeof data_retention_schedule;
  "data_retention/support": typeof data_retention_support;
  "data_retention/sweeps": typeof data_retention_sweeps;
  demo_build_address: typeof demo_build_address;
  demo_builder_proposals: typeof demo_builder_proposals;
  "demo_builder_proposals/boundary": typeof demo_builder_proposals_boundary;
  "demo_builder_proposals/dashboard": typeof demo_builder_proposals_dashboard;
  "demo_builder_proposals/milestones": typeof demo_builder_proposals_milestones;
  "demo_builder_proposals/projections": typeof demo_builder_proposals_projections;
  "demo_builder_proposals/seed": typeof demo_builder_proposals_seed;
  "demo_builder_proposals/shared": typeof demo_builder_proposals_shared;
  demo_drawflow: typeof demo_drawflow;
  "demo_drawflow/access": typeof demo_drawflow_access;
  "demo_drawflow/bootstrap": typeof demo_drawflow_bootstrap;
  "demo_drawflow/completion": typeof demo_drawflow_completion;
  "demo_drawflow/dashboard": typeof demo_drawflow_dashboard;
  "demo_drawflow/data": typeof demo_drawflow_data;
  "demo_drawflow/evidence": typeof demo_drawflow_evidence;
  "demo_drawflow/issues": typeof demo_drawflow_issues;
  "demo_drawflow/lifecycle": typeof demo_drawflow_lifecycle;
  "demo_drawflow/milestones": typeof demo_drawflow_milestones;
  "demo_drawflow/projection": typeof demo_drawflow_projection;
  "demo_drawflow/proposal": typeof demo_drawflow_proposal;
  "demo_drawflow/seed": typeof demo_drawflow_seed;
  "demo_drawflow/site_visits": typeof demo_drawflow_site_visits;
  "demo_drawflow/submission": typeof demo_drawflow_submission;
  "demo_drawflow/validation": typeof demo_drawflow_validation;
  "demo_drawflow/workspace": typeof demo_drawflow_workspace;
  demo_drawflow_backoffice: typeof demo_drawflow_backoffice;
  "demo_drawflow_backoffice/build_mutations": typeof demo_drawflow_backoffice_build_mutations;
  "demo_drawflow_backoffice/contractors": typeof demo_drawflow_backoffice_contractors;
  "demo_drawflow_backoffice/draw": typeof demo_drawflow_backoffice_draw;
  "demo_drawflow_backoffice/notes": typeof demo_drawflow_backoffice_notes;
  "demo_drawflow_backoffice/resolver": typeof demo_drawflow_backoffice_resolver;
  "demo_drawflow_backoffice/seed": typeof demo_drawflow_backoffice_seed;
  "demo_drawflow_backoffice/view": typeof demo_drawflow_backoffice_view;
  demo_personas: typeof demo_personas;
  demo_settings: typeof demo_settings;
  "demo_settings/core": typeof demo_settings_core;
  "demo_settings/handlers": typeof demo_settings_handlers;
  "demo_settings/shared": typeof demo_settings_shared;
  "demo_settings/storage": typeof demo_settings_storage;
  "demo_settings/validation": typeof demo_settings_validation;
  demo_site_visit_guidance: typeof demo_site_visit_guidance;
  demo_site_visit_tokens: typeof demo_site_visit_tokens;
  demo_timeline_plans: typeof demo_timeline_plans;
  "demo_timeline_plans/access": typeof demo_timeline_plans_access;
  "demo_timeline_plans/admin": typeof demo_timeline_plans_admin;
  "demo_timeline_plans/backoffice": typeof demo_timeline_plans_backoffice;
  "demo_timeline_plans/capital": typeof demo_timeline_plans_capital;
  "demo_timeline_plans/core": typeof demo_timeline_plans_core;
  "demo_timeline_plans/draws": typeof demo_timeline_plans_draws;
  "demo_timeline_plans/evidence": typeof demo_timeline_plans_evidence;
  "demo_timeline_plans/milestones": typeof demo_timeline_plans_milestones;
  "demo_timeline_plans/plan": typeof demo_timeline_plans_plan;
  "demo_timeline_plans/shared": typeof demo_timeline_plans_shared;
  "demo_timeline_plans/workspace": typeof demo_timeline_plans_workspace;
  demo_timeline_snapshots: typeof demo_timeline_snapshots;
  email_transport: typeof email_transport;
  evidence_preview: typeof evidence_preview;
  fairLendConfig: typeof fairLendConfig;
  fluent: typeof fluent;
  gardenSuiteTemplate: typeof gardenSuiteTemplate;
  http: typeof http;
  identity_invitation_emails: typeof identity_invitation_emails;
  lenderOrganizationAccess: typeof lenderOrganizationAccess;
  lenderOrganizationReviewPolicies: typeof lenderOrganizationReviewPolicies;
  lenderOrganizations: typeof lenderOrganizations;
  lender_assignment_manifest: typeof lender_assignment_manifest;
  "lender_organizations/contracts": typeof lender_organizations_contracts;
  "lender_organizations/helpers": typeof lender_organizations_helpers;
  "lender_organizations/member_deactivation": typeof lender_organizations_member_deactivation;
  lender_portal: typeof lender_portal;
  "lender_portal/build_detail": typeof lender_portal_build_detail;
  "lender_portal/collaboration": typeof lender_portal_collaboration;
  "lender_portal/collaboration_access": typeof lender_portal_collaboration_access;
  "lender_portal/collaboration_asset_actions": typeof lender_portal_collaboration_asset_actions;
  "lender_portal/collaboration_assets": typeof lender_portal_collaboration_assets;
  "lender_portal/dashboard": typeof lender_portal_dashboard;
  "lender_portal/draw_queue": typeof lender_portal_draw_queue;
  "lender_portal/proposals": typeof lender_portal_proposals;
  "lender_portal/shared": typeof lender_portal_shared;
  lender_portal_access: typeof lender_portal_access;
  lender_portal_notifications: typeof lender_portal_notifications;
  "lender_portal_notifications/contracts": typeof lender_portal_notifications_contracts;
  "lender_portal_notifications/enqueue": typeof lender_portal_notifications_enqueue;
  "lender_portal_notifications/shared": typeof lender_portal_notifications_shared;
  "lender_portal_notifications/suppression": typeof lender_portal_notifications_suppression;
  lender_portal_pagination: typeof lender_portal_pagination;
  lender_portal_phase3: typeof lender_portal_phase3;
  lender_portal_phase4: typeof lender_portal_phase4;
  lender_portal_phase5: typeof lender_portal_phase5;
  "lender_portal_phase5/evidence": typeof lender_portal_phase5_evidence;
  "lender_portal_phase5/lifecycle": typeof lender_portal_phase5_lifecycle;
  "lender_portal_phase5/projections": typeof lender_portal_phase5_projections;
  "lender_portal_phase5/shared": typeof lender_portal_phase5_shared;
  "lender_portal_phase5/site_visits": typeof lender_portal_phase5_site_visits;
  lender_portal_phase5_contracts: typeof lender_portal_phase5_contracts;
  lender_portal_phase9: typeof lender_portal_phase9;
  "lender_portal_phase9/inventory": typeof lender_portal_phase9_inventory;
  "lender_portal_phase9/runs": typeof lender_portal_phase9_runs;
  "lender_portal_phase9/shared": typeof lender_portal_phase9_shared;
  "lender_portal_phase9/snapshot": typeof lender_portal_phase9_snapshot;
  "lender_portal_phase9/snapshot_support": typeof lender_portal_phase9_snapshot_support;
  lender_portal_phase9_contracts: typeof lender_portal_phase9_contracts;
  lender_portal_release: typeof lender_portal_release;
  "lender_portal_release/helpers": typeof lender_portal_release_helpers;
  migrations: typeof migrations;
  "migrations/context": typeof migrations_context;
  "migrations/legacy": typeof migrations_legacy;
  "migrations/lender_member_permissions": typeof migrations_lender_member_permissions;
  "migrations/lender_organization": typeof migrations_lender_organization;
  "migrations/phase3": typeof migrations_phase3;
  "migrations/phase9": typeof migrations_phase9;
  milestone_start: typeof milestone_start;
  production_proposal_detail: typeof production_proposal_detail;
  production_proposal_lifecycle: typeof production_proposal_lifecycle;
  production_proposals: typeof production_proposals;
  "production_proposals/active_build_completion": typeof production_proposals_active_build_completion;
  "production_proposals/active_build_contractors": typeof production_proposals_active_build_contractors;
  "production_proposals/active_build_detail": typeof production_proposals_active_build_detail;
  "production_proposals/active_build_documents": typeof production_proposals_active_build_documents;
  "production_proposals/active_build_draw_migration": typeof production_proposals_active_build_draw_migration;
  "production_proposals/active_build_draws": typeof production_proposals_active_build_draws;
  "production_proposals/active_build_evidence_storage": typeof production_proposals_active_build_evidence_storage;
  "production_proposals/active_build_planning": typeof production_proposals_active_build_planning;
  "production_proposals/active_build_profile": typeof production_proposals_active_build_profile;
  "production_proposals/active_build_projection": typeof production_proposals_active_build_projection;
  "production_proposals/active_build_reviews": typeof production_proposals_active_build_reviews;
  "production_proposals/active_build_site_visits": typeof production_proposals_active_build_site_visits;
  "production_proposals/active_build_staff": typeof production_proposals_active_build_staff;
  "production_proposals/active_build_submilestone_evidence": typeof production_proposals_active_build_submilestone_evidence;
  "production_proposals/active_build_submilestone_execution": typeof production_proposals_active_build_submilestone_execution;
  "production_proposals/active_build_timeline": typeof production_proposals_active_build_timeline;
  "production_proposals/active_capital_evidence": typeof production_proposals_active_capital_evidence;
  "production_proposals/active_cost": typeof production_proposals_active_cost;
  "production_proposals/active_funding": typeof production_proposals_active_funding;
  "production_proposals/active_planning": typeof production_proposals_active_planning;
  "production_proposals/assignment_manifest": typeof production_proposals_assignment_manifest;
  "production_proposals/audit_helpers": typeof production_proposals_audit_helpers;
  "production_proposals/authorization_core": typeof production_proposals_authorization_core;
  "production_proposals/backoffice_proposal_views": typeof production_proposals_backoffice_proposal_views;
  "production_proposals/brokerage_draws": typeof production_proposals_brokerage_draws;
  "production_proposals/brokerage_site_visits": typeof production_proposals_brokerage_site_visits;
  "production_proposals/builder_onboarding": typeof production_proposals_builder_onboarding;
  "production_proposals/builder_staff_access": typeof production_proposals_builder_staff_access;
  "production_proposals/builder_staff_persistence": typeof production_proposals_builder_staff_persistence;
  "production_proposals/calendar_contracts": typeof production_proposals_calendar_contracts;
  "production_proposals/calendar_scheduling": typeof production_proposals_calendar_scheduling;
  "production_proposals/calendar_workspaces": typeof production_proposals_calendar_workspaces;
  "production_proposals/confirmation_history_helpers": typeof production_proposals_confirmation_history_helpers;
  "production_proposals/contractor_active_helpers": typeof production_proposals_contractor_active_helpers;
  "production_proposals/contractor_assignments": typeof production_proposals_contractor_assignments;
  "production_proposals/contractor_policy_helpers": typeof production_proposals_contractor_policy_helpers;
  "production_proposals/contractor_profiles": typeof production_proposals_contractor_profiles;
  "production_proposals/contractor_proposal_helpers": typeof production_proposals_contractor_proposal_helpers;
  "production_proposals/contractor_relationship_helpers": typeof production_proposals_contractor_relationship_helpers;
  "production_proposals/contracts_foundation": typeof production_proposals_contracts_foundation;
  "production_proposals/contracts_workflow": typeof production_proposals_contracts_workflow;
  "production_proposals/directory_cards": typeof production_proposals_directory_cards;
  "production_proposals/integration_helpers": typeof production_proposals_integration_helpers;
  "production_proposals/integrations": typeof production_proposals_integrations;
  "production_proposals/legacy_seed": typeof production_proposals_legacy_seed;
  "production_proposals/lender_assignment_auth": typeof production_proposals_lender_assignment_auth;
  "production_proposals/lender_detail": typeof production_proposals_lender_detail;
  "production_proposals/notification_delivery_helpers": typeof production_proposals_notification_delivery_helpers;
  "production_proposals/operations_handoffs": typeof production_proposals_operations_handoffs;
  "production_proposals/operations_helpers": typeof production_proposals_operations_helpers;
  "production_proposals/proposal_activation": typeof production_proposals_proposal_activation;
  "production_proposals/proposal_assignment_admin": typeof production_proposals_proposal_assignment_admin;
  "production_proposals/proposal_assignments": typeof production_proposals_proposal_assignments;
  "production_proposals/proposal_build_cost": typeof production_proposals_proposal_build_cost;
  "production_proposals/proposal_capital": typeof production_proposals_proposal_capital;
  "production_proposals/proposal_claim": typeof production_proposals_proposal_claim;
  "production_proposals/proposal_confirmation": typeof production_proposals_proposal_confirmation;
  "production_proposals/proposal_copy_audit": typeof production_proposals_proposal_copy_audit;
  "production_proposals/proposal_cost_persistence": typeof production_proposals_proposal_cost_persistence;
  "production_proposals/proposal_cost_validation": typeof production_proposals_proposal_cost_validation;
  "production_proposals/proposal_detail_projection": typeof production_proposals_proposal_detail_projection;
  "production_proposals/proposal_draft_model": typeof production_proposals_proposal_draft_model;
  "production_proposals/proposal_draft_persistence": typeof production_proposals_proposal_draft_persistence;
  "production_proposals/proposal_draw_plan": typeof production_proposals_proposal_draw_plan;
  "production_proposals/proposal_evidence_completion": typeof production_proposals_proposal_evidence_completion;
  "production_proposals/proposal_lender_approval": typeof production_proposals_proposal_lender_approval;
  "production_proposals/proposal_review_commands": typeof production_proposals_proposal_review_commands;
  "production_proposals/proposal_review_reads": typeof production_proposals_proposal_review_reads;
  "production_proposals/proposal_review_restore": typeof production_proposals_proposal_review_restore;
  "production_proposals/proposal_revision_commands": typeof production_proposals_proposal_revision_commands;
  "production_proposals/proposal_seed": typeof production_proposals_proposal_seed;
  "production_proposals/proposal_settings": typeof production_proposals_proposal_settings;
  "production_proposals/proposal_timeline": typeof production_proposals_proposal_timeline;
  "production_proposals/proposal_timeline_workspace": typeof production_proposals_proposal_timeline_workspace;
  "production_proposals/review_lifecycle_helpers": typeof production_proposals_review_lifecycle_helpers;
  "production_proposals/roster_contracts": typeof production_proposals_roster_contracts;
  "production_proposals/roster_projection_helpers": typeof production_proposals_roster_projection_helpers;
  "production_proposals/roster_queries": typeof production_proposals_roster_queries;
  "production_proposals/roster_views": typeof production_proposals_roster_views;
  "production_proposals/seed_default_builders": typeof production_proposals_seed_default_builders;
  "production_proposals/seed_foundation": typeof production_proposals_seed_foundation;
  "production_proposals/seed_scenario": typeof production_proposals_seed_scenario;
  "production_proposals/seed_template_defaults": typeof production_proposals_seed_template_defaults;
  "production_proposals/seed_template_writer": typeof production_proposals_seed_template_writer;
  "production_proposals/settings_helpers": typeof production_proposals_settings_helpers;
  "production_proposals/site_visit_calendar": typeof production_proposals_site_visit_calendar;
  "production_proposals/site_visit_helpers": typeof production_proposals_site_visit_helpers;
  "production_proposals/storage_helpers": typeof production_proposals_storage_helpers;
  "production_proposals/submilestone_commands": typeof production_proposals_submilestone_commands;
  proposal_collaboration: typeof proposal_collaboration;
  "proposal_collaboration/audit": typeof proposal_collaboration_audit;
  "proposal_collaboration/authorization": typeof proposal_collaboration_authorization;
  "proposal_collaboration/context": typeof proposal_collaboration_context;
  "proposal_collaboration/contracts": typeof proposal_collaboration_contracts;
  "proposal_collaboration/identity": typeof proposal_collaboration_identity;
  "proposal_collaboration/presence": typeof proposal_collaboration_presence;
  "proposal_collaboration/snapshots": typeof proposal_collaboration_snapshots;
  proposal_collaboration_model: typeof proposal_collaboration_model;
  proposal_revision_lender_snapshot: typeof proposal_revision_lender_snapshot;
  qaIdentityCleanup: typeof qaIdentityCleanup;
  qaIdentityCleanupTables: typeof qaIdentityCleanupTables;
  quote_authoring_access: typeof quote_authoring_access;
  quote_comparisons: typeof quote_comparisons;
  "quote_comparisons/access": typeof quote_comparisons_access;
  "quote_comparisons/candidates": typeof quote_comparisons_candidates;
  "quote_comparisons/contract": typeof quote_comparisons_contract;
  "quote_comparisons/read": typeof quote_comparisons_read;
  quote_invitation_access: typeof quote_invitation_access;
  "quote_invitation_access/core": typeof quote_invitation_access_core;
  "quote_invitation_access/handlers": typeof quote_invitation_access_handlers;
  "quote_invitation_access/projection": typeof quote_invitation_access_projection;
  "quote_invitation_access/recipient": typeof quote_invitation_access_recipient;
  quote_notifications: typeof quote_notifications;
  "quote_notifications/contracts": typeof quote_notifications_contracts;
  "quote_notifications/delivery": typeof quote_notifications_delivery;
  "quote_notifications/email": typeof quote_notifications_email;
  "quote_notifications/projection": typeof quote_notifications_projection;
  "quote_notifications/scheduling": typeof quote_notifications_scheduling;
  quote_preferred: typeof quote_preferred;
  quote_response_drafts: typeof quote_response_drafts;
  "quote_response_drafts/attachments": typeof quote_response_drafts_attachments;
  "quote_response_drafts/core": typeof quote_response_drafts_core;
  "quote_response_drafts/migration": typeof quote_response_drafts_migration;
  "quote_response_drafts/mutations": typeof quote_response_drafts_mutations;
  "quote_response_drafts/read_write": typeof quote_response_drafts_read_write;
  quote_response_submissions: typeof quote_response_submissions;
  "quote_response_submissions/core": typeof quote_response_submissions_core;
  "quote_response_submissions/mutations": typeof quote_response_submissions_mutations;
  "quote_response_submissions/projection": typeof quote_response_submissions_projection;
  "quote_response_submissions/read": typeof quote_response_submissions_read;
  "quote_response_submissions/validation": typeof quote_response_submissions_validation;
  quote_response_template_migrations: typeof quote_response_template_migrations;
  quote_response_templates: typeof quote_response_templates;
  "quote_response_templates/core": typeof quote_response_templates_core;
  "quote_response_templates/handlers": typeof quote_response_templates_handlers;
  quote_round_lifecycle: typeof quote_round_lifecycle;
  "quote_round_lifecycle/core": typeof quote_round_lifecycle_core;
  "quote_round_lifecycle/invitation_handlers": typeof quote_round_lifecycle_invitation_handlers;
  "quote_round_lifecycle/round_handlers": typeof quote_round_lifecycle_round_handlers;
  quote_rounds: typeof quote_rounds;
  "quote_rounds/access": typeof quote_rounds_access;
  "quote_rounds/composer": typeof quote_rounds_composer;
  "quote_rounds/contracts": typeof quote_rounds_contracts;
  "quote_rounds/draft_mutations": typeof quote_rounds_draft_mutations;
  "quote_rounds/draft_validation": typeof quote_rounds_draft_validation;
  "quote_rounds/list": typeof quote_rounds_list;
  "quote_rounds/mutations": typeof quote_rounds_mutations;
  "quote_rounds/projections": typeof quote_rounds_projections;
  "quote_rounds/publication": typeof quote_rounds_publication;
  "quote_rounds/publication_validation": typeof quote_rounds_publication_validation;
  recipient_delivery_projection: typeof recipient_delivery_projection;
  "schema/build_collaboration_01": typeof schema_build_collaboration_01;
  "schema/build_collaboration_02": typeof schema_build_collaboration_02;
  "schema/build_collaboration_03": typeof schema_build_collaboration_03;
  "schema/build_collaboration_04": typeof schema_build_collaboration_04;
  "schema/build_workspace_01": typeof schema_build_workspace_01;
  "schema/build_workspace_02": typeof schema_build_workspace_02;
  "schema/build_workspace_03": typeof schema_build_workspace_03;
  "schema/communications_01": typeof schema_communications_01;
  "schema/core_01": typeof schema_core_01;
  "schema/demo_01": typeof schema_demo_01;
  "schema/demo_02": typeof schema_demo_02;
  "schema/identity_01": typeof schema_identity_01;
  "schema/proposal_lifecycle_01": typeof schema_proposal_lifecycle_01;
  "schema/proposal_lifecycle_02": typeof schema_proposal_lifecycle_02;
  "schema/quoting_01": typeof schema_quoting_01;
  "schema/quoting_02": typeof schema_quoting_02;
  "schema/retention_01": typeof schema_retention_01;
  "schema/review_policy_defaults_01": typeof schema_review_policy_defaults_01;
  "schema/scheduling_01": typeof schema_scheduling_01;
  "schema/validators": typeof schema_validators;
  siteVisitGuidance: typeof siteVisitGuidance;
  submilestone_field_guidance: typeof submilestone_field_guidance;
  submilestone_scope_contracts: typeof submilestone_scope_contracts;
  "submilestone_scope_contracts/decisions": typeof submilestone_scope_contracts_decisions;
  "submilestone_scope_contracts/revisions": typeof submilestone_scope_contracts_revisions;
  "submilestone_scope_contracts/shared": typeof submilestone_scope_contracts_shared;
  submilestone_scope_guidance_migrations: typeof submilestone_scope_guidance_migrations;
  todos: typeof todos;
  types: typeof types;
  workosManagement: typeof workosManagement;
  "workosManagement/context": typeof workosManagement_context;
  "workosManagement/directory": typeof workosManagement_directory;
  "workosManagement/invitationEmails": typeof workosManagement_invitationEmails;
  "workosManagement/membership": typeof workosManagement_membership;
  "workosManagement/shared": typeof workosManagement_shared;
  "workosManagement/transfer": typeof workosManagement_transfer;
  workosProjection: typeof workosProjection;
  "workosProjection/events": typeof workosProjection_events;
  "workosProjection/reads": typeof workosProjection_reads;
  workos_permission_access: typeof workos_permission_access;
}>;

/**
 * A utility for referencing Convex functions in your app's public API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = api.myModule.myFunction;
 * ```
 */
export declare const api: FilterApi<
  typeof fullApi,
  FunctionReference<any, "public">
>;

/**
 * A utility for referencing Convex functions in your app's internal API.
 *
 * Usage:
 * ```js
 * const myFunctionReference = internal.myModule.myFunction;
 * ```
 */
export declare const internal: FilterApi<
  typeof fullApi,
  FunctionReference<any, "internal">
>;

export declare const components: {
  agent: import("@convex-dev/agent/_generated/component.js").ComponentApi<"agent">;
  migrations: import("@convex-dev/migrations/_generated/component.js").ComponentApi<"migrations">;
  workOSAuthKit: import("@convex-dev/workos-authkit/_generated/component.js").ComponentApi<"workOSAuthKit">;
  presence: import("@convex-dev/presence/_generated/component.js").ComponentApi<"presence">;
  resend: import("@convex-dev/resend/_generated/component.js").ComponentApi<"resend">;
  buildCollaborationSearchWorkpool: import("@convex-dev/workpool/_generated/component.js").ComponentApi<"buildCollaborationSearchWorkpool">;
  timeline: import("convex-timeline/_generated/component.js").ComponentApi<"timeline">;
};
