/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as DemoWorkosRouteImport } from './routes/demo/workos'
import { Route as DemoTanstackQueryRouteImport } from './routes/demo/tanstack-query'
import { Route as DemoConvexRouteImport } from './routes/demo/convex'
import { Route as ApiAuthSignUpRouteImport } from './routes/api/auth/sign-up'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'

const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoWorkosRoute = DemoWorkosRouteImport.update({
  id: '/demo/workos',
  path: '/demo/workos',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoTanstackQueryRoute = DemoTanstackQueryRouteImport.update({
  id: '/demo/tanstack-query',
  path: '/demo/tanstack-query',
  getParentRoute: () => rootRouteImport,
} as any)
const DemoConvexRoute = DemoConvexRouteImport.update({
  id: '/demo/convex',
  path: '/demo/convex',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignUpRoute = ApiAuthSignUpRouteImport.update({
  id: '/api/auth/sign-up',
  path: '/api/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/callback': typeof CallbackRoute
  '/demo/convex': typeof DemoConvexRoute
  '/demo/tanstack-query': typeof DemoTanstackQueryRoute
  '/demo/workos': typeof DemoWorkosRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/callback'
    | '/demo/convex'
    | '/demo/tanstack-query'
    | '/demo/workos'
    | '/api/auth/sign-in'
    | '/api/auth/sign-up'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/callback'
    | '/demo/convex'
    | '/demo/tanstack-query'
    | '/demo/workos'
    | '/api/auth/sign-in'
    | '/api/auth/sign-up'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/callback'
    | '/demo/convex'
    | '/demo/tanstack-query'
    | '/demo/workos'
    | '/api/auth/sign-in'
    | '/api/auth/sign-up'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  CallbackRoute: typeof CallbackRoute
  DemoConvexRoute: typeof DemoConvexRoute
  DemoTanstackQueryRoute: typeof DemoTanstackQueryRoute
  DemoWorkosRoute: typeof DemoWorkosRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiAuthSignUpRoute: typeof ApiAuthSignUpRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/workos': {
      id: '/demo/workos'
      path: '/demo/workos'
      fullPath: '/demo/workos'
      preLoaderRoute: typeof DemoWorkosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/tanstack-query': {
      id: '/demo/tanstack-query'
      path: '/demo/tanstack-query'
      fullPath: '/demo/tanstack-query'
      preLoaderRoute: typeof DemoTanstackQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/demo/convex': {
      id: '/demo/convex'
      path: '/demo/convex'
      fullPath: '/demo/convex'
      preLoaderRoute: typeof DemoConvexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-up': {
      id: '/api/auth/sign-up'
      path: '/api/auth/sign-up'
      fullPath: '/api/auth/sign-up'
      preLoaderRoute: typeof ApiAuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  CallbackRoute: CallbackRoute,
  DemoConvexRoute: DemoConvexRoute,
  DemoTanstackQueryRoute: DemoTanstackQueryRoute,
  DemoWorkosRoute: DemoWorkosRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiAuthSignUpRoute: ApiAuthSignUpRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
