/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ProtectedAccessRouteImport } from './routes/protected-access'
import { Route as ProposalPreviewRouteImport } from './routes/proposal-preview'
import { Route as CallbackRouteImport } from './routes/callback'
import { Route as HomeownerRouteRouteImport } from './routes/homeowner/route'
import { Route as ContractorRouteRouteImport } from './routes/contractor/route'
import { Route as BuilderStaffRouteRouteImport } from './routes/builder-staff/route'
import { Route as BuilderRouteRouteImport } from './routes/builder/route'
import { Route as BackofficeRouteRouteImport } from './routes/backoffice/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HomeownerIndexRouteImport } from './routes/homeowner/index'
import { Route as ContractorIndexRouteImport } from './routes/contractor/index'
import { Route as BuilderIndexRouteImport } from './routes/builder/index'
import { Route as BuilderStaffIndexRouteImport } from './routes/builder-staff/index'
import { Route as BackofficeIndexRouteImport } from './routes/backoffice/index'
import { Route as QuoteInvitationMagicTokenRouteImport } from './routes/quote-invitation.$magicToken'
import { Route as PrototypeSystemPostsRouteImport } from './routes/prototype/system-posts'
import { Route as PrototypeContractorWorkRouteImport } from './routes/prototype/contractor-work'
import { Route as PrototypeContractorQuotesRouteImport } from './routes/prototype/contractor-quotes'
import { Route as PrototypeBuildCollaborationRouteImport } from './routes/prototype/build-collaboration'
import { Route as PrototypeActionItemsRouteImport } from './routes/prototype/action-items'
import { Route as ProposalClaimClaimTokenRouteImport } from './routes/proposal-claim.$claimToken'
import { Route as LenderPrototypeRouteImport } from './routes/lender.prototype'
import { Route as LenderProposalConfirmationPrototypeRouteImport } from './routes/lender.proposal-confirmation-prototype'
import { Route as LenderOrganizationManagementPrototypeRouteImport } from './routes/lender.organization-management-prototype'
import { Route as LenderMilestonesPrototypeRouteImport } from './routes/lender.milestones-prototype'
import { Route as LenderDrawsPrototypeRouteImport } from './routes/lender.draws-prototype'
import { Route as LenderDrawReviewSheetPrototypeRouteImport } from './routes/lender.draw-review-sheet-prototype'
import { Route as LenderDrawReviewPrototypeRouteImport } from './routes/lender.draw-review-prototype'
import { Route as ContractorWorkRouteImport } from './routes/contractor/work'
import { Route as ContractorScheduleRouteImport } from './routes/contractor/schedule'
import { Route as ContractorProfileRouteImport } from './routes/contractor/profile'
import { Route as ContractorOnboardingRouteImport } from './routes/contractor/onboarding'
import { Route as ContractorEvidenceRouteImport } from './routes/contractor/evidence'
import { Route as BuilderQuoteTemplatesRouteImport } from './routes/builder/quote-templates'
import { Route as BuilderStaffQuoteTemplatesRouteImport } from './routes/builder-staff/quote-templates'
import { Route as BackofficeUserManagementRouteImport } from './routes/backoffice/user-management'
import { Route as BackofficeOnboardContractorRouteImport } from './routes/backoffice/onboard-contractor'
import { Route as BackofficeOnboardBuilderRouteImport } from './routes/backoffice/onboard-builder'
import { Route as BackofficeIntegrationsRouteImport } from './routes/backoffice/integrations'
import { Route as ApiReleaseRouteImport } from './routes/api/release'
import { Route as BuilderProposalsRouteRouteImport } from './routes/builder/proposals/route'
import { Route as BuilderStaffProposalsRouteRouteImport } from './routes/builder-staff/proposals/route'
import { Route as BuilderStaffBuildsRouteRouteImport } from './routes/builder-staff/builds/route'
import { Route as BackofficeSiteVisitsRouteRouteImport } from './routes/backoffice/site-visits/route'
import { Route as BackofficeSettingsRouteRouteImport } from './routes/backoffice/settings/route'
import { Route as BackofficeProposalsRouteRouteImport } from './routes/backoffice/proposals/route'
import { Route as BackofficeDrawsRouteRouteImport } from './routes/backoffice/draws/route'
import { Route as BackofficeContractorsRouteRouteImport } from './routes/backoffice/contractors/route'
import { Route as BackofficeBuildsRouteRouteImport } from './routes/backoffice/builds/route'
import { Route as BackofficeBuildersRouteRouteImport } from './routes/backoffice/builders/route'
import { Route as ContractorProposalsIndexRouteImport } from './routes/contractor/proposals/index'
import { Route as ContractorBuildsIndexRouteImport } from './routes/contractor/builds/index'
import { Route as BuilderProposalsIndexRouteImport } from './routes/builder/proposals/index'
import { Route as BuilderStaffProposalsIndexRouteImport } from './routes/builder-staff/proposals/index'
import { Route as BuilderStaffBuildsIndexRouteImport } from './routes/builder-staff/builds/index'
import { Route as BackofficeSettingsIndexRouteImport } from './routes/backoffice/settings/index'
import { Route as BackofficeProposalsIndexRouteImport } from './routes/backoffice/proposals/index'
import { Route as BackofficeContractorsIndexRouteImport } from './routes/backoffice/contractors/index'
import { Route as BackofficeBuildsIndexRouteImport } from './routes/backoffice/builds/index'
import { Route as BackofficeBuildersIndexRouteImport } from './routes/backoffice/builders/index'
import { Route as NewsitevisitBuildIdSiteVisitTokenRouteImport } from './routes/newsitevisit.$buildId.$siteVisitToken'
import { Route as HomeownerBuildsBuildIdRouteImport } from './routes/homeowner/builds/$buildId'
import { Route as ContractorProposalsProposalIdRouteImport } from './routes/contractor/proposals/$proposalId'
import { Route as ContractorBuildsBuildIdRouteImport } from './routes/contractor/builds/$buildId'
import { Route as BuilderProposalsNewRouteImport } from './routes/builder/proposals/new'
import { Route as BuilderContractorsContractorIdRouteImport } from './routes/builder/contractors/$contractorId'
import { Route as BackofficeProposalsUnassignedRouteImport } from './routes/backoffice/proposals/unassigned'
import { Route as BackofficeProposalsReviewRequirementsPrototypeRouteImport } from './routes/backoffice/proposals/review-requirements-prototype'
import { Route as BackofficeProposalsNewRouteImport } from './routes/backoffice/proposals/new'
import { Route as BackofficeProposalsPlanIdRouteImport } from './routes/backoffice/proposals.$planId'
import { Route as BackofficeContractorsOnboardingRouteImport } from './routes/backoffice/contractors/onboarding'
import { Route as BackofficeContractorsContractorIdRouteImport } from './routes/backoffice/contractors/$contractorId'
import { Route as BackofficeBuildersBuilderIdRouteImport } from './routes/backoffice/builders/builderId'
import { Route as ApiAuthSignUpRouteImport } from './routes/api/auth/sign-up'
import { Route as ApiAuthSignInRouteImport } from './routes/api/auth/sign-in'
import { Route as BuilderProposalsProposalIdRouteRouteImport } from './routes/builder/proposals/$proposalId/route'
import { Route as BuilderStaffProposalsProposalIdRouteRouteImport } from './routes/builder-staff/proposals/$proposalId/route'
import { Route as BackofficeBuildsBuildIdRouteRouteImport } from './routes/backoffice/builds/$buildId/route'
import { Route as BuilderProposalsProposalIdIndexRouteImport } from './routes/builder/proposals/$proposalId/index'
import { Route as BuilderBuildsBuildIdIndexRouteImport } from './routes/builder/builds/$buildId/index'
import { Route as BuilderStaffProposalsProposalIdIndexRouteImport } from './routes/builder-staff/proposals/$proposalId/index'
import { Route as BuilderStaffBuildsBuildIdIndexRouteImport } from './routes/builder-staff/builds/$buildId/index'
import { Route as BackofficeBuildsBuildIdIndexRouteImport } from './routes/backoffice/builds/$buildId/index'
import { Route as BuilderBuildsBuildIdQuotesNewRouteImport } from './routes/builder/builds/$buildId/quotes/new'
import { Route as BuilderStaffBuildsBuildIdQuotesNewRouteImport } from './routes/builder-staff/builds/$buildId/quotes/new'
import { Route as BackofficeBuildsBuildIdQuotesNewRouteImport } from './routes/backoffice/builds/$buildId/quotes/new'

const ProtectedAccessRoute = ProtectedAccessRouteImport.update({
  id: '/protected-access',
  path: '/protected-access',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalPreviewRoute = ProposalPreviewRouteImport.update({
  id: '/proposal-preview',
  path: '/proposal-preview',
  getParentRoute: () => rootRouteImport,
} as any)
const CallbackRoute = CallbackRouteImport.update({
  id: '/callback',
  path: '/callback',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeownerRouteRoute = HomeownerRouteRouteImport.update({
  id: '/homeowner',
  path: '/homeowner',
  getParentRoute: () => rootRouteImport,
} as any)
const ContractorRouteRoute = ContractorRouteRouteImport.update({
  id: '/contractor',
  path: '/contractor',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderStaffRouteRoute = BuilderStaffRouteRouteImport.update({
  id: '/builder-staff',
  path: '/builder-staff',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderRouteRoute = BuilderRouteRouteImport.update({
  id: '/builder',
  path: '/builder',
  getParentRoute: () => rootRouteImport,
} as any)
const BackofficeRouteRoute = BackofficeRouteRouteImport.update({
  id: '/backoffice',
  path: '/backoffice',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HomeownerIndexRoute = HomeownerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => HomeownerRouteRoute,
} as any)
const ContractorIndexRoute = ContractorIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const BuilderIndexRoute = BuilderIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuilderRouteRoute,
} as any)
const BuilderStaffIndexRoute = BuilderStaffIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuilderStaffRouteRoute,
} as any)
const BackofficeIndexRoute = BackofficeIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackofficeRouteRoute,
} as any)
const QuoteInvitationMagicTokenRoute =
  QuoteInvitationMagicTokenRouteImport.update({
    id: '/quote-invitation/$magicToken',
    path: '/quote-invitation/$magicToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrototypeSystemPostsRoute = PrototypeSystemPostsRouteImport.update({
  id: '/prototype/system-posts',
  path: '/prototype/system-posts',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeContractorWorkRoute = PrototypeContractorWorkRouteImport.update({
  id: '/prototype/contractor-work',
  path: '/prototype/contractor-work',
  getParentRoute: () => rootRouteImport,
} as any)
const PrototypeContractorQuotesRoute =
  PrototypeContractorQuotesRouteImport.update({
    id: '/prototype/contractor-quotes',
    path: '/prototype/contractor-quotes',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrototypeBuildCollaborationRoute =
  PrototypeBuildCollaborationRouteImport.update({
    id: '/prototype/build-collaboration',
    path: '/prototype/build-collaboration',
    getParentRoute: () => rootRouteImport,
  } as any)
const PrototypeActionItemsRoute = PrototypeActionItemsRouteImport.update({
  id: '/prototype/action-items',
  path: '/prototype/action-items',
  getParentRoute: () => rootRouteImport,
} as any)
const ProposalClaimClaimTokenRoute = ProposalClaimClaimTokenRouteImport.update({
  id: '/proposal-claim/$claimToken',
  path: '/proposal-claim/$claimToken',
  getParentRoute: () => rootRouteImport,
} as any)
const LenderPrototypeRoute = LenderPrototypeRouteImport.update({
  id: '/lender/prototype',
  path: '/lender/prototype',
  getParentRoute: () => rootRouteImport,
} as any)
const LenderProposalConfirmationPrototypeRoute =
  LenderProposalConfirmationPrototypeRouteImport.update({
    id: '/lender/proposal-confirmation-prototype',
    path: '/lender/proposal-confirmation-prototype',
    getParentRoute: () => rootRouteImport,
  } as any)
const LenderOrganizationManagementPrototypeRoute =
  LenderOrganizationManagementPrototypeRouteImport.update({
    id: '/lender/organization-management-prototype',
    path: '/lender/organization-management-prototype',
    getParentRoute: () => rootRouteImport,
  } as any)
const LenderMilestonesPrototypeRoute =
  LenderMilestonesPrototypeRouteImport.update({
    id: '/lender/milestones-prototype',
    path: '/lender/milestones-prototype',
    getParentRoute: () => rootRouteImport,
  } as any)
const LenderDrawsPrototypeRoute = LenderDrawsPrototypeRouteImport.update({
  id: '/lender/draws-prototype',
  path: '/lender/draws-prototype',
  getParentRoute: () => rootRouteImport,
} as any)
const LenderDrawReviewSheetPrototypeRoute =
  LenderDrawReviewSheetPrototypeRouteImport.update({
    id: '/lender/draw-review-sheet-prototype',
    path: '/lender/draw-review-sheet-prototype',
    getParentRoute: () => rootRouteImport,
  } as any)
const LenderDrawReviewPrototypeRoute =
  LenderDrawReviewPrototypeRouteImport.update({
    id: '/lender/draw-review-prototype',
    path: '/lender/draw-review-prototype',
    getParentRoute: () => rootRouteImport,
  } as any)
const ContractorWorkRoute = ContractorWorkRouteImport.update({
  id: '/work',
  path: '/work',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const ContractorScheduleRoute = ContractorScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const ContractorProfileRoute = ContractorProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const ContractorOnboardingRoute = ContractorOnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const ContractorEvidenceRoute = ContractorEvidenceRouteImport.update({
  id: '/evidence',
  path: '/evidence',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const BuilderQuoteTemplatesRoute = BuilderQuoteTemplatesRouteImport.update({
  id: '/quote-templates',
  path: '/quote-templates',
  getParentRoute: () => BuilderRouteRoute,
} as any)
const BuilderStaffQuoteTemplatesRoute =
  BuilderStaffQuoteTemplatesRouteImport.update({
    id: '/quote-templates',
    path: '/quote-templates',
    getParentRoute: () => BuilderStaffRouteRoute,
  } as any)
const BackofficeUserManagementRoute =
  BackofficeUserManagementRouteImport.update({
    id: '/user-management',
    path: '/user-management',
    getParentRoute: () => BackofficeRouteRoute,
  } as any)
const BackofficeOnboardContractorRoute =
  BackofficeOnboardContractorRouteImport.update({
    id: '/onboard-contractor',
    path: '/onboard-contractor',
    getParentRoute: () => BackofficeRouteRoute,
  } as any)
const BackofficeOnboardBuilderRoute =
  BackofficeOnboardBuilderRouteImport.update({
    id: '/onboard-builder',
    path: '/onboard-builder',
    getParentRoute: () => BackofficeRouteRoute,
  } as any)
const BackofficeIntegrationsRoute = BackofficeIntegrationsRouteImport.update({
  id: '/integrations',
  path: '/integrations',
  getParentRoute: () => BackofficeRouteRoute,
} as any)
const ApiReleaseRoute = ApiReleaseRouteImport.update({
  id: '/api/release',
  path: '/api/release',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderProposalsRouteRoute = BuilderProposalsRouteRouteImport.update({
  id: '/proposals',
  path: '/proposals',
  getParentRoute: () => BuilderRouteRoute,
} as any)
const BuilderStaffProposalsRouteRoute =
  BuilderStaffProposalsRouteRouteImport.update({
    id: '/proposals',
    path: '/proposals',
    getParentRoute: () => BuilderStaffRouteRoute,
  } as any)
const BuilderStaffBuildsRouteRoute = BuilderStaffBuildsRouteRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => BuilderStaffRouteRoute,
} as any)
const BackofficeSiteVisitsRouteRoute =
  BackofficeSiteVisitsRouteRouteImport.update({
    id: '/site-visits',
    path: '/site-visits',
    getParentRoute: () => BackofficeRouteRoute,
  } as any)
const BackofficeSettingsRouteRoute = BackofficeSettingsRouteRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => BackofficeRouteRoute,
} as any)
const BackofficeProposalsRouteRoute =
  BackofficeProposalsRouteRouteImport.update({
    id: '/proposals',
    path: '/proposals',
    getParentRoute: () => BackofficeRouteRoute,
  } as any)
const BackofficeDrawsRouteRoute = BackofficeDrawsRouteRouteImport.update({
  id: '/draws',
  path: '/draws',
  getParentRoute: () => BackofficeRouteRoute,
} as any)
const BackofficeContractorsRouteRoute =
  BackofficeContractorsRouteRouteImport.update({
    id: '/contractors',
    path: '/contractors',
    getParentRoute: () => BackofficeRouteRoute,
  } as any)
const BackofficeBuildsRouteRoute = BackofficeBuildsRouteRouteImport.update({
  id: '/builds',
  path: '/builds',
  getParentRoute: () => BackofficeRouteRoute,
} as any)
const BackofficeBuildersRouteRoute = BackofficeBuildersRouteRouteImport.update({
  id: '/builders',
  path: '/builders',
  getParentRoute: () => BackofficeRouteRoute,
} as any)
const ContractorProposalsIndexRoute =
  ContractorProposalsIndexRouteImport.update({
    id: '/proposals/',
    path: '/proposals/',
    getParentRoute: () => ContractorRouteRoute,
  } as any)
const ContractorBuildsIndexRoute = ContractorBuildsIndexRouteImport.update({
  id: '/builds/',
  path: '/builds/',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const BuilderProposalsIndexRoute = BuilderProposalsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuilderProposalsRouteRoute,
} as any)
const BuilderStaffProposalsIndexRoute =
  BuilderStaffProposalsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BuilderStaffProposalsRouteRoute,
  } as any)
const BuilderStaffBuildsIndexRoute = BuilderStaffBuildsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BuilderStaffBuildsRouteRoute,
} as any)
const BackofficeSettingsIndexRoute = BackofficeSettingsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackofficeSettingsRouteRoute,
} as any)
const BackofficeProposalsIndexRoute =
  BackofficeProposalsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BackofficeProposalsRouteRoute,
  } as any)
const BackofficeContractorsIndexRoute =
  BackofficeContractorsIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BackofficeContractorsRouteRoute,
  } as any)
const BackofficeBuildsIndexRoute = BackofficeBuildsIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackofficeBuildsRouteRoute,
} as any)
const BackofficeBuildersIndexRoute = BackofficeBuildersIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BackofficeBuildersRouteRoute,
} as any)
const NewsitevisitBuildIdSiteVisitTokenRoute =
  NewsitevisitBuildIdSiteVisitTokenRouteImport.update({
    id: '/newsitevisit/$buildId/$siteVisitToken',
    path: '/newsitevisit/$buildId/$siteVisitToken',
    getParentRoute: () => rootRouteImport,
  } as any)
const HomeownerBuildsBuildIdRoute = HomeownerBuildsBuildIdRouteImport.update({
  id: '/builds/$buildId',
  path: '/builds/$buildId',
  getParentRoute: () => HomeownerRouteRoute,
} as any)
const ContractorProposalsProposalIdRoute =
  ContractorProposalsProposalIdRouteImport.update({
    id: '/proposals/$proposalId',
    path: '/proposals/$proposalId',
    getParentRoute: () => ContractorRouteRoute,
  } as any)
const ContractorBuildsBuildIdRoute = ContractorBuildsBuildIdRouteImport.update({
  id: '/builds/$buildId',
  path: '/builds/$buildId',
  getParentRoute: () => ContractorRouteRoute,
} as any)
const BuilderProposalsNewRoute = BuilderProposalsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BuilderProposalsRouteRoute,
} as any)
const BuilderContractorsContractorIdRoute =
  BuilderContractorsContractorIdRouteImport.update({
    id: '/contractors/$contractorId',
    path: '/contractors/$contractorId',
    getParentRoute: () => BuilderRouteRoute,
  } as any)
const BackofficeProposalsUnassignedRoute =
  BackofficeProposalsUnassignedRouteImport.update({
    id: '/unassigned',
    path: '/unassigned',
    getParentRoute: () => BackofficeProposalsRouteRoute,
  } as any)
const BackofficeProposalsReviewRequirementsPrototypeRoute =
  BackofficeProposalsReviewRequirementsPrototypeRouteImport.update({
    id: '/review-requirements-prototype',
    path: '/review-requirements-prototype',
    getParentRoute: () => BackofficeProposalsRouteRoute,
  } as any)
const BackofficeProposalsNewRoute = BackofficeProposalsNewRouteImport.update({
  id: '/new',
  path: '/new',
  getParentRoute: () => BackofficeProposalsRouteRoute,
} as any)
const BackofficeProposalsPlanIdRoute =
  BackofficeProposalsPlanIdRouteImport.update({
    id: '/$planId',
    path: '/$planId',
    getParentRoute: () => BackofficeProposalsRouteRoute,
  } as any)
const BackofficeContractorsOnboardingRoute =
  BackofficeContractorsOnboardingRouteImport.update({
    id: '/onboarding',
    path: '/onboarding',
    getParentRoute: () => BackofficeContractorsRouteRoute,
  } as any)
const BackofficeContractorsContractorIdRoute =
  BackofficeContractorsContractorIdRouteImport.update({
    id: '/$contractorId',
    path: '/$contractorId',
    getParentRoute: () => BackofficeContractorsRouteRoute,
  } as any)
const BackofficeBuildersBuilderIdRoute =
  BackofficeBuildersBuilderIdRouteImport.update({
    id: '/builderId',
    path: '/builderId',
    getParentRoute: () => BackofficeBuildersRouteRoute,
  } as any)
const ApiAuthSignUpRoute = ApiAuthSignUpRouteImport.update({
  id: '/api/auth/sign-up',
  path: '/api/auth/sign-up',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiAuthSignInRoute = ApiAuthSignInRouteImport.update({
  id: '/api/auth/sign-in',
  path: '/api/auth/sign-in',
  getParentRoute: () => rootRouteImport,
} as any)
const BuilderProposalsProposalIdRouteRoute =
  BuilderProposalsProposalIdRouteRouteImport.update({
    id: '/$proposalId',
    path: '/$proposalId',
    getParentRoute: () => BuilderProposalsRouteRoute,
  } as any)
const BuilderStaffProposalsProposalIdRouteRoute =
  BuilderStaffProposalsProposalIdRouteRouteImport.update({
    id: '/$proposalId',
    path: '/$proposalId',
    getParentRoute: () => BuilderStaffProposalsRouteRoute,
  } as any)
const BackofficeBuildsBuildIdRouteRoute =
  BackofficeBuildsBuildIdRouteRouteImport.update({
    id: '/$buildId',
    path: '/$buildId',
    getParentRoute: () => BackofficeBuildsRouteRoute,
  } as any)
const BuilderProposalsProposalIdIndexRoute =
  BuilderProposalsProposalIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BuilderProposalsProposalIdRouteRoute,
  } as any)
const BuilderBuildsBuildIdIndexRoute =
  BuilderBuildsBuildIdIndexRouteImport.update({
    id: '/builds/$buildId/',
    path: '/builds/$buildId/',
    getParentRoute: () => BuilderRouteRoute,
  } as any)
const BuilderStaffProposalsProposalIdIndexRoute =
  BuilderStaffProposalsProposalIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BuilderStaffProposalsProposalIdRouteRoute,
  } as any)
const BuilderStaffBuildsBuildIdIndexRoute =
  BuilderStaffBuildsBuildIdIndexRouteImport.update({
    id: '/$buildId/',
    path: '/$buildId/',
    getParentRoute: () => BuilderStaffBuildsRouteRoute,
  } as any)
const BackofficeBuildsBuildIdIndexRoute =
  BackofficeBuildsBuildIdIndexRouteImport.update({
    id: '/',
    path: '/',
    getParentRoute: () => BackofficeBuildsBuildIdRouteRoute,
  } as any)
const BuilderBuildsBuildIdQuotesNewRoute =
  BuilderBuildsBuildIdQuotesNewRouteImport.update({
    id: '/builds/$buildId/quotes/new',
    path: '/builds/$buildId/quotes/new',
    getParentRoute: () => BuilderRouteRoute,
  } as any)
const BuilderStaffBuildsBuildIdQuotesNewRoute =
  BuilderStaffBuildsBuildIdQuotesNewRouteImport.update({
    id: '/$buildId/quotes/new',
    path: '/$buildId/quotes/new',
    getParentRoute: () => BuilderStaffBuildsRouteRoute,
  } as any)
const BackofficeBuildsBuildIdQuotesNewRoute =
  BackofficeBuildsBuildIdQuotesNewRouteImport.update({
    id: '/quotes/new',
    path: '/quotes/new',
    getParentRoute: () => BackofficeBuildsBuildIdRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRouteRouteWithChildren
  '/builder': typeof BuilderRouteRouteWithChildren
  '/builder-staff': typeof BuilderStaffRouteRouteWithChildren
  '/contractor': typeof ContractorRouteRouteWithChildren
  '/homeowner': typeof HomeownerRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/proposal-preview': typeof ProposalPreviewRoute
  '/protected-access': typeof ProtectedAccessRoute
  '/backoffice/builders': typeof BackofficeBuildersRouteRouteWithChildren
  '/backoffice/builds': typeof BackofficeBuildsRouteRouteWithChildren
  '/backoffice/contractors': typeof BackofficeContractorsRouteRouteWithChildren
  '/backoffice/draws': typeof BackofficeDrawsRouteRoute
  '/backoffice/proposals': typeof BackofficeProposalsRouteRouteWithChildren
  '/backoffice/settings': typeof BackofficeSettingsRouteRouteWithChildren
  '/backoffice/site-visits': typeof BackofficeSiteVisitsRouteRoute
  '/builder-staff/builds': typeof BuilderStaffBuildsRouteRouteWithChildren
  '/builder-staff/proposals': typeof BuilderStaffProposalsRouteRouteWithChildren
  '/builder/proposals': typeof BuilderProposalsRouteRouteWithChildren
  '/api/release': typeof ApiReleaseRoute
  '/backoffice/integrations': typeof BackofficeIntegrationsRoute
  '/backoffice/onboard-builder': typeof BackofficeOnboardBuilderRoute
  '/backoffice/onboard-contractor': typeof BackofficeOnboardContractorRoute
  '/backoffice/user-management': typeof BackofficeUserManagementRoute
  '/builder-staff/quote-templates': typeof BuilderStaffQuoteTemplatesRoute
  '/builder/quote-templates': typeof BuilderQuoteTemplatesRoute
  '/contractor/evidence': typeof ContractorEvidenceRoute
  '/contractor/onboarding': typeof ContractorOnboardingRoute
  '/contractor/profile': typeof ContractorProfileRoute
  '/contractor/schedule': typeof ContractorScheduleRoute
  '/contractor/work': typeof ContractorWorkRoute
  '/lender/draw-review-prototype': typeof LenderDrawReviewPrototypeRoute
  '/lender/draw-review-sheet-prototype': typeof LenderDrawReviewSheetPrototypeRoute
  '/lender/draws-prototype': typeof LenderDrawsPrototypeRoute
  '/lender/milestones-prototype': typeof LenderMilestonesPrototypeRoute
  '/lender/organization-management-prototype': typeof LenderOrganizationManagementPrototypeRoute
  '/lender/proposal-confirmation-prototype': typeof LenderProposalConfirmationPrototypeRoute
  '/lender/prototype': typeof LenderPrototypeRoute
  '/proposal-claim/$claimToken': typeof ProposalClaimClaimTokenRoute
  '/prototype/action-items': typeof PrototypeActionItemsRoute
  '/prototype/build-collaboration': typeof PrototypeBuildCollaborationRoute
  '/prototype/contractor-quotes': typeof PrototypeContractorQuotesRoute
  '/prototype/contractor-work': typeof PrototypeContractorWorkRoute
  '/prototype/system-posts': typeof PrototypeSystemPostsRoute
  '/quote-invitation/$magicToken': typeof QuoteInvitationMagicTokenRoute
  '/backoffice/': typeof BackofficeIndexRoute
  '/builder-staff/': typeof BuilderStaffIndexRoute
  '/builder/': typeof BuilderIndexRoute
  '/contractor/': typeof ContractorIndexRoute
  '/homeowner/': typeof HomeownerIndexRoute
  '/backoffice/builds/$buildId': typeof BackofficeBuildsBuildIdRouteRouteWithChildren
  '/builder-staff/proposals/$proposalId': typeof BuilderStaffProposalsProposalIdRouteRouteWithChildren
  '/builder/proposals/$proposalId': typeof BuilderProposalsProposalIdRouteRouteWithChildren
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/backoffice/builders/builderId': typeof BackofficeBuildersBuilderIdRoute
  '/backoffice/contractors/$contractorId': typeof BackofficeContractorsContractorIdRoute
  '/backoffice/contractors/onboarding': typeof BackofficeContractorsOnboardingRoute
  '/backoffice/proposals/$planId': typeof BackofficeProposalsPlanIdRoute
  '/backoffice/proposals/new': typeof BackofficeProposalsNewRoute
  '/backoffice/proposals/review-requirements-prototype': typeof BackofficeProposalsReviewRequirementsPrototypeRoute
  '/backoffice/proposals/unassigned': typeof BackofficeProposalsUnassignedRoute
  '/builder/contractors/$contractorId': typeof BuilderContractorsContractorIdRoute
  '/builder/proposals/new': typeof BuilderProposalsNewRoute
  '/contractor/builds/$buildId': typeof ContractorBuildsBuildIdRoute
  '/contractor/proposals/$proposalId': typeof ContractorProposalsProposalIdRoute
  '/homeowner/builds/$buildId': typeof HomeownerBuildsBuildIdRoute
  '/newsitevisit/$buildId/$siteVisitToken': typeof NewsitevisitBuildIdSiteVisitTokenRoute
  '/backoffice/builders/': typeof BackofficeBuildersIndexRoute
  '/backoffice/builds/': typeof BackofficeBuildsIndexRoute
  '/backoffice/contractors/': typeof BackofficeContractorsIndexRoute
  '/backoffice/proposals/': typeof BackofficeProposalsIndexRoute
  '/backoffice/settings/': typeof BackofficeSettingsIndexRoute
  '/builder-staff/builds/': typeof BuilderStaffBuildsIndexRoute
  '/builder-staff/proposals/': typeof BuilderStaffProposalsIndexRoute
  '/builder/proposals/': typeof BuilderProposalsIndexRoute
  '/contractor/builds/': typeof ContractorBuildsIndexRoute
  '/contractor/proposals/': typeof ContractorProposalsIndexRoute
  '/backoffice/builds/$buildId/': typeof BackofficeBuildsBuildIdIndexRoute
  '/builder-staff/builds/$buildId/': typeof BuilderStaffBuildsBuildIdIndexRoute
  '/builder-staff/proposals/$proposalId/': typeof BuilderStaffProposalsProposalIdIndexRoute
  '/builder/builds/$buildId/': typeof BuilderBuildsBuildIdIndexRoute
  '/builder/proposals/$proposalId/': typeof BuilderProposalsProposalIdIndexRoute
  '/backoffice/builds/$buildId/quotes/new': typeof BackofficeBuildsBuildIdQuotesNewRoute
  '/builder-staff/builds/$buildId/quotes/new': typeof BuilderStaffBuildsBuildIdQuotesNewRoute
  '/builder/builds/$buildId/quotes/new': typeof BuilderBuildsBuildIdQuotesNewRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/callback': typeof CallbackRoute
  '/proposal-preview': typeof ProposalPreviewRoute
  '/protected-access': typeof ProtectedAccessRoute
  '/backoffice/draws': typeof BackofficeDrawsRouteRoute
  '/backoffice/site-visits': typeof BackofficeSiteVisitsRouteRoute
  '/api/release': typeof ApiReleaseRoute
  '/backoffice/integrations': typeof BackofficeIntegrationsRoute
  '/backoffice/onboard-builder': typeof BackofficeOnboardBuilderRoute
  '/backoffice/onboard-contractor': typeof BackofficeOnboardContractorRoute
  '/backoffice/user-management': typeof BackofficeUserManagementRoute
  '/builder-staff/quote-templates': typeof BuilderStaffQuoteTemplatesRoute
  '/builder/quote-templates': typeof BuilderQuoteTemplatesRoute
  '/contractor/evidence': typeof ContractorEvidenceRoute
  '/contractor/onboarding': typeof ContractorOnboardingRoute
  '/contractor/profile': typeof ContractorProfileRoute
  '/contractor/schedule': typeof ContractorScheduleRoute
  '/contractor/work': typeof ContractorWorkRoute
  '/lender/draw-review-prototype': typeof LenderDrawReviewPrototypeRoute
  '/lender/draw-review-sheet-prototype': typeof LenderDrawReviewSheetPrototypeRoute
  '/lender/draws-prototype': typeof LenderDrawsPrototypeRoute
  '/lender/milestones-prototype': typeof LenderMilestonesPrototypeRoute
  '/lender/organization-management-prototype': typeof LenderOrganizationManagementPrototypeRoute
  '/lender/proposal-confirmation-prototype': typeof LenderProposalConfirmationPrototypeRoute
  '/lender/prototype': typeof LenderPrototypeRoute
  '/proposal-claim/$claimToken': typeof ProposalClaimClaimTokenRoute
  '/prototype/action-items': typeof PrototypeActionItemsRoute
  '/prototype/build-collaboration': typeof PrototypeBuildCollaborationRoute
  '/prototype/contractor-quotes': typeof PrototypeContractorQuotesRoute
  '/prototype/contractor-work': typeof PrototypeContractorWorkRoute
  '/prototype/system-posts': typeof PrototypeSystemPostsRoute
  '/quote-invitation/$magicToken': typeof QuoteInvitationMagicTokenRoute
  '/backoffice': typeof BackofficeIndexRoute
  '/builder-staff': typeof BuilderStaffIndexRoute
  '/builder': typeof BuilderIndexRoute
  '/contractor': typeof ContractorIndexRoute
  '/homeowner': typeof HomeownerIndexRoute
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/backoffice/builders/builderId': typeof BackofficeBuildersBuilderIdRoute
  '/backoffice/contractors/$contractorId': typeof BackofficeContractorsContractorIdRoute
  '/backoffice/contractors/onboarding': typeof BackofficeContractorsOnboardingRoute
  '/backoffice/proposals/$planId': typeof BackofficeProposalsPlanIdRoute
  '/backoffice/proposals/new': typeof BackofficeProposalsNewRoute
  '/backoffice/proposals/review-requirements-prototype': typeof BackofficeProposalsReviewRequirementsPrototypeRoute
  '/backoffice/proposals/unassigned': typeof BackofficeProposalsUnassignedRoute
  '/builder/contractors/$contractorId': typeof BuilderContractorsContractorIdRoute
  '/builder/proposals/new': typeof BuilderProposalsNewRoute
  '/contractor/builds/$buildId': typeof ContractorBuildsBuildIdRoute
  '/contractor/proposals/$proposalId': typeof ContractorProposalsProposalIdRoute
  '/homeowner/builds/$buildId': typeof HomeownerBuildsBuildIdRoute
  '/newsitevisit/$buildId/$siteVisitToken': typeof NewsitevisitBuildIdSiteVisitTokenRoute
  '/backoffice/builders': typeof BackofficeBuildersIndexRoute
  '/backoffice/builds': typeof BackofficeBuildsIndexRoute
  '/backoffice/contractors': typeof BackofficeContractorsIndexRoute
  '/backoffice/proposals': typeof BackofficeProposalsIndexRoute
  '/backoffice/settings': typeof BackofficeSettingsIndexRoute
  '/builder-staff/builds': typeof BuilderStaffBuildsIndexRoute
  '/builder-staff/proposals': typeof BuilderStaffProposalsIndexRoute
  '/builder/proposals': typeof BuilderProposalsIndexRoute
  '/contractor/builds': typeof ContractorBuildsIndexRoute
  '/contractor/proposals': typeof ContractorProposalsIndexRoute
  '/backoffice/builds/$buildId': typeof BackofficeBuildsBuildIdIndexRoute
  '/builder-staff/builds/$buildId': typeof BuilderStaffBuildsBuildIdIndexRoute
  '/builder-staff/proposals/$proposalId': typeof BuilderStaffProposalsProposalIdIndexRoute
  '/builder/builds/$buildId': typeof BuilderBuildsBuildIdIndexRoute
  '/builder/proposals/$proposalId': typeof BuilderProposalsProposalIdIndexRoute
  '/backoffice/builds/$buildId/quotes/new': typeof BackofficeBuildsBuildIdQuotesNewRoute
  '/builder-staff/builds/$buildId/quotes/new': typeof BuilderStaffBuildsBuildIdQuotesNewRoute
  '/builder/builds/$buildId/quotes/new': typeof BuilderBuildsBuildIdQuotesNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/backoffice': typeof BackofficeRouteRouteWithChildren
  '/builder': typeof BuilderRouteRouteWithChildren
  '/builder-staff': typeof BuilderStaffRouteRouteWithChildren
  '/contractor': typeof ContractorRouteRouteWithChildren
  '/homeowner': typeof HomeownerRouteRouteWithChildren
  '/callback': typeof CallbackRoute
  '/proposal-preview': typeof ProposalPreviewRoute
  '/protected-access': typeof ProtectedAccessRoute
  '/backoffice/builders': typeof BackofficeBuildersRouteRouteWithChildren
  '/backoffice/builds': typeof BackofficeBuildsRouteRouteWithChildren
  '/backoffice/contractors': typeof BackofficeContractorsRouteRouteWithChildren
  '/backoffice/draws': typeof BackofficeDrawsRouteRoute
  '/backoffice/proposals': typeof BackofficeProposalsRouteRouteWithChildren
  '/backoffice/settings': typeof BackofficeSettingsRouteRouteWithChildren
  '/backoffice/site-visits': typeof BackofficeSiteVisitsRouteRoute
  '/builder-staff/builds': typeof BuilderStaffBuildsRouteRouteWithChildren
  '/builder-staff/proposals': typeof BuilderStaffProposalsRouteRouteWithChildren
  '/builder/proposals': typeof BuilderProposalsRouteRouteWithChildren
  '/api/release': typeof ApiReleaseRoute
  '/backoffice/integrations': typeof BackofficeIntegrationsRoute
  '/backoffice/onboard-builder': typeof BackofficeOnboardBuilderRoute
  '/backoffice/onboard-contractor': typeof BackofficeOnboardContractorRoute
  '/backoffice/user-management': typeof BackofficeUserManagementRoute
  '/builder-staff/quote-templates': typeof BuilderStaffQuoteTemplatesRoute
  '/builder/quote-templates': typeof BuilderQuoteTemplatesRoute
  '/contractor/evidence': typeof ContractorEvidenceRoute
  '/contractor/onboarding': typeof ContractorOnboardingRoute
  '/contractor/profile': typeof ContractorProfileRoute
  '/contractor/schedule': typeof ContractorScheduleRoute
  '/contractor/work': typeof ContractorWorkRoute
  '/lender/draw-review-prototype': typeof LenderDrawReviewPrototypeRoute
  '/lender/draw-review-sheet-prototype': typeof LenderDrawReviewSheetPrototypeRoute
  '/lender/draws-prototype': typeof LenderDrawsPrototypeRoute
  '/lender/milestones-prototype': typeof LenderMilestonesPrototypeRoute
  '/lender/organization-management-prototype': typeof LenderOrganizationManagementPrototypeRoute
  '/lender/proposal-confirmation-prototype': typeof LenderProposalConfirmationPrototypeRoute
  '/lender/prototype': typeof LenderPrototypeRoute
  '/proposal-claim/$claimToken': typeof ProposalClaimClaimTokenRoute
  '/prototype/action-items': typeof PrototypeActionItemsRoute
  '/prototype/build-collaboration': typeof PrototypeBuildCollaborationRoute
  '/prototype/contractor-quotes': typeof PrototypeContractorQuotesRoute
  '/prototype/contractor-work': typeof PrototypeContractorWorkRoute
  '/prototype/system-posts': typeof PrototypeSystemPostsRoute
  '/quote-invitation/$magicToken': typeof QuoteInvitationMagicTokenRoute
  '/backoffice/': typeof BackofficeIndexRoute
  '/builder-staff/': typeof BuilderStaffIndexRoute
  '/builder/': typeof BuilderIndexRoute
  '/contractor/': typeof ContractorIndexRoute
  '/homeowner/': typeof HomeownerIndexRoute
  '/backoffice/builds/$buildId': typeof BackofficeBuildsBuildIdRouteRouteWithChildren
  '/builder-staff/proposals/$proposalId': typeof BuilderStaffProposalsProposalIdRouteRouteWithChildren
  '/builder/proposals/$proposalId': typeof BuilderProposalsProposalIdRouteRouteWithChildren
  '/api/auth/sign-in': typeof ApiAuthSignInRoute
  '/api/auth/sign-up': typeof ApiAuthSignUpRoute
  '/backoffice/builders/builderId': typeof BackofficeBuildersBuilderIdRoute
  '/backoffice/contractors/$contractorId': typeof BackofficeContractorsContractorIdRoute
  '/backoffice/contractors/onboarding': typeof BackofficeContractorsOnboardingRoute
  '/backoffice/proposals/$planId': typeof BackofficeProposalsPlanIdRoute
  '/backoffice/proposals/new': typeof BackofficeProposalsNewRoute
  '/backoffice/proposals/review-requirements-prototype': typeof BackofficeProposalsReviewRequirementsPrototypeRoute
  '/backoffice/proposals/unassigned': typeof BackofficeProposalsUnassignedRoute
  '/builder/contractors/$contractorId': typeof BuilderContractorsContractorIdRoute
  '/builder/proposals/new': typeof BuilderProposalsNewRoute
  '/contractor/builds/$buildId': typeof ContractorBuildsBuildIdRoute
  '/contractor/proposals/$proposalId': typeof ContractorProposalsProposalIdRoute
  '/homeowner/builds/$buildId': typeof HomeownerBuildsBuildIdRoute
  '/newsitevisit/$buildId/$siteVisitToken': typeof NewsitevisitBuildIdSiteVisitTokenRoute
  '/backoffice/builders/': typeof BackofficeBuildersIndexRoute
  '/backoffice/builds/': typeof BackofficeBuildsIndexRoute
  '/backoffice/contractors/': typeof BackofficeContractorsIndexRoute
  '/backoffice/proposals/': typeof BackofficeProposalsIndexRoute
  '/backoffice/settings/': typeof BackofficeSettingsIndexRoute
  '/builder-staff/builds/': typeof BuilderStaffBuildsIndexRoute
  '/builder-staff/proposals/': typeof BuilderStaffProposalsIndexRoute
  '/builder/proposals/': typeof BuilderProposalsIndexRoute
  '/contractor/builds/': typeof ContractorBuildsIndexRoute
  '/contractor/proposals/': typeof ContractorProposalsIndexRoute
  '/backoffice/builds/$buildId/': typeof BackofficeBuildsBuildIdIndexRoute
  '/builder-staff/builds/$buildId/': typeof BuilderStaffBuildsBuildIdIndexRoute
  '/builder-staff/proposals/$proposalId/': typeof BuilderStaffProposalsProposalIdIndexRoute
  '/builder/builds/$buildId/': typeof BuilderBuildsBuildIdIndexRoute
  '/builder/proposals/$proposalId/': typeof BuilderProposalsProposalIdIndexRoute
  '/backoffice/builds/$buildId/quotes/new': typeof BackofficeBuildsBuildIdQuotesNewRoute
  '/builder-staff/builds/$buildId/quotes/new': typeof BuilderStaffBuildsBuildIdQuotesNewRoute
  '/builder/builds/$buildId/quotes/new': typeof BuilderBuildsBuildIdQuotesNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/backoffice'
    | '/builder'
    | '/builder-staff'
    | '/contractor'
    | '/homeowner'
    | '/callback'
    | '/proposal-preview'
    | '/protected-access'
    | '/backoffice/builders'
    | '/backoffice/builds'
    | '/backoffice/contractors'
    | '/backoffice/draws'
    | '/backoffice/proposals'
    | '/backoffice/settings'
    | '/backoffice/site-visits'
    | '/builder-staff/builds'
    | '/builder-staff/proposals'
    | '/builder/proposals'
    | '/api/release'
    | '/backoffice/integrations'
    | '/backoffice/onboard-builder'
    | '/backoffice/onboard-contractor'
    | '/backoffice/user-management'
    | '/builder-staff/quote-templates'
    | '/builder/quote-templates'
    | '/contractor/evidence'
    | '/contractor/onboarding'
    | '/contractor/profile'
    | '/contractor/schedule'
    | '/contractor/work'
    | '/lender/draw-review-prototype'
    | '/lender/draw-review-sheet-prototype'
    | '/lender/draws-prototype'
    | '/lender/milestones-prototype'
    | '/lender/organization-management-prototype'
    | '/lender/proposal-confirmation-prototype'
    | '/lender/prototype'
    | '/proposal-claim/$claimToken'
    | '/prototype/action-items'
    | '/prototype/build-collaboration'
    | '/prototype/contractor-quotes'
    | '/prototype/contractor-work'
    | '/prototype/system-posts'
    | '/quote-invitation/$magicToken'
    | '/backoffice/'
    | '/builder-staff/'
    | '/builder/'
    | '/contractor/'
    | '/homeowner/'
    | '/backoffice/builds/$buildId'
    | '/builder-staff/proposals/$proposalId'
    | '/builder/proposals/$proposalId'
    | '/api/auth/sign-in'
    | '/api/auth/sign-up'
    | '/backoffice/builders/builderId'
    | '/backoffice/contractors/$contractorId'
    | '/backoffice/contractors/onboarding'
    | '/backoffice/proposals/$planId'
    | '/backoffice/proposals/new'
    | '/backoffice/proposals/review-requirements-prototype'
    | '/backoffice/proposals/unassigned'
    | '/builder/contractors/$contractorId'
    | '/builder/proposals/new'
    | '/contractor/builds/$buildId'
    | '/contractor/proposals/$proposalId'
    | '/homeowner/builds/$buildId'
    | '/newsitevisit/$buildId/$siteVisitToken'
    | '/backoffice/builders/'
    | '/backoffice/builds/'
    | '/backoffice/contractors/'
    | '/backoffice/proposals/'
    | '/backoffice/settings/'
    | '/builder-staff/builds/'
    | '/builder-staff/proposals/'
    | '/builder/proposals/'
    | '/contractor/builds/'
    | '/contractor/proposals/'
    | '/backoffice/builds/$buildId/'
    | '/builder-staff/builds/$buildId/'
    | '/builder-staff/proposals/$proposalId/'
    | '/builder/builds/$buildId/'
    | '/builder/proposals/$proposalId/'
    | '/backoffice/builds/$buildId/quotes/new'
    | '/builder-staff/builds/$buildId/quotes/new'
    | '/builder/builds/$buildId/quotes/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/callback'
    | '/proposal-preview'
    | '/protected-access'
    | '/backoffice/draws'
    | '/backoffice/site-visits'
    | '/api/release'
    | '/backoffice/integrations'
    | '/backoffice/onboard-builder'
    | '/backoffice/onboard-contractor'
    | '/backoffice/user-management'
    | '/builder-staff/quote-templates'
    | '/builder/quote-templates'
    | '/contractor/evidence'
    | '/contractor/onboarding'
    | '/contractor/profile'
    | '/contractor/schedule'
    | '/contractor/work'
    | '/lender/draw-review-prototype'
    | '/lender/draw-review-sheet-prototype'
    | '/lender/draws-prototype'
    | '/lender/milestones-prototype'
    | '/lender/organization-management-prototype'
    | '/lender/proposal-confirmation-prototype'
    | '/lender/prototype'
    | '/proposal-claim/$claimToken'
    | '/prototype/action-items'
    | '/prototype/build-collaboration'
    | '/prototype/contractor-quotes'
    | '/prototype/contractor-work'
    | '/prototype/system-posts'
    | '/quote-invitation/$magicToken'
    | '/backoffice'
    | '/builder-staff'
    | '/builder'
    | '/contractor'
    | '/homeowner'
    | '/api/auth/sign-in'
    | '/api/auth/sign-up'
    | '/backoffice/builders/builderId'
    | '/backoffice/contractors/$contractorId'
    | '/backoffice/contractors/onboarding'
    | '/backoffice/proposals/$planId'
    | '/backoffice/proposals/new'
    | '/backoffice/proposals/review-requirements-prototype'
    | '/backoffice/proposals/unassigned'
    | '/builder/contractors/$contractorId'
    | '/builder/proposals/new'
    | '/contractor/builds/$buildId'
    | '/contractor/proposals/$proposalId'
    | '/homeowner/builds/$buildId'
    | '/newsitevisit/$buildId/$siteVisitToken'
    | '/backoffice/builders'
    | '/backoffice/builds'
    | '/backoffice/contractors'
    | '/backoffice/proposals'
    | '/backoffice/settings'
    | '/builder-staff/builds'
    | '/builder-staff/proposals'
    | '/builder/proposals'
    | '/contractor/builds'
    | '/contractor/proposals'
    | '/backoffice/builds/$buildId'
    | '/builder-staff/builds/$buildId'
    | '/builder-staff/proposals/$proposalId'
    | '/builder/builds/$buildId'
    | '/builder/proposals/$proposalId'
    | '/backoffice/builds/$buildId/quotes/new'
    | '/builder-staff/builds/$buildId/quotes/new'
    | '/builder/builds/$buildId/quotes/new'
  id:
    | '__root__'
    | '/'
    | '/backoffice'
    | '/builder'
    | '/builder-staff'
    | '/contractor'
    | '/homeowner'
    | '/callback'
    | '/proposal-preview'
    | '/protected-access'
    | '/backoffice/builders'
    | '/backoffice/builds'
    | '/backoffice/contractors'
    | '/backoffice/draws'
    | '/backoffice/proposals'
    | '/backoffice/settings'
    | '/backoffice/site-visits'
    | '/builder-staff/builds'
    | '/builder-staff/proposals'
    | '/builder/proposals'
    | '/api/release'
    | '/backoffice/integrations'
    | '/backoffice/onboard-builder'
    | '/backoffice/onboard-contractor'
    | '/backoffice/user-management'
    | '/builder-staff/quote-templates'
    | '/builder/quote-templates'
    | '/contractor/evidence'
    | '/contractor/onboarding'
    | '/contractor/profile'
    | '/contractor/schedule'
    | '/contractor/work'
    | '/lender/draw-review-prototype'
    | '/lender/draw-review-sheet-prototype'
    | '/lender/draws-prototype'
    | '/lender/milestones-prototype'
    | '/lender/organization-management-prototype'
    | '/lender/proposal-confirmation-prototype'
    | '/lender/prototype'
    | '/proposal-claim/$claimToken'
    | '/prototype/action-items'
    | '/prototype/build-collaboration'
    | '/prototype/contractor-quotes'
    | '/prototype/contractor-work'
    | '/prototype/system-posts'
    | '/quote-invitation/$magicToken'
    | '/backoffice/'
    | '/builder-staff/'
    | '/builder/'
    | '/contractor/'
    | '/homeowner/'
    | '/backoffice/builds/$buildId'
    | '/builder-staff/proposals/$proposalId'
    | '/builder/proposals/$proposalId'
    | '/api/auth/sign-in'
    | '/api/auth/sign-up'
    | '/backoffice/builders/builderId'
    | '/backoffice/contractors/$contractorId'
    | '/backoffice/contractors/onboarding'
    | '/backoffice/proposals/$planId'
    | '/backoffice/proposals/new'
    | '/backoffice/proposals/review-requirements-prototype'
    | '/backoffice/proposals/unassigned'
    | '/builder/contractors/$contractorId'
    | '/builder/proposals/new'
    | '/contractor/builds/$buildId'
    | '/contractor/proposals/$proposalId'
    | '/homeowner/builds/$buildId'
    | '/newsitevisit/$buildId/$siteVisitToken'
    | '/backoffice/builders/'
    | '/backoffice/builds/'
    | '/backoffice/contractors/'
    | '/backoffice/proposals/'
    | '/backoffice/settings/'
    | '/builder-staff/builds/'
    | '/builder-staff/proposals/'
    | '/builder/proposals/'
    | '/contractor/builds/'
    | '/contractor/proposals/'
    | '/backoffice/builds/$buildId/'
    | '/builder-staff/builds/$buildId/'
    | '/builder-staff/proposals/$proposalId/'
    | '/builder/builds/$buildId/'
    | '/builder/proposals/$proposalId/'
    | '/backoffice/builds/$buildId/quotes/new'
    | '/builder-staff/builds/$buildId/quotes/new'
    | '/builder/builds/$buildId/quotes/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BackofficeRouteRoute: typeof BackofficeRouteRouteWithChildren
  BuilderRouteRoute: typeof BuilderRouteRouteWithChildren
  BuilderStaffRouteRoute: typeof BuilderStaffRouteRouteWithChildren
  ContractorRouteRoute: typeof ContractorRouteRouteWithChildren
  HomeownerRouteRoute: typeof HomeownerRouteRouteWithChildren
  CallbackRoute: typeof CallbackRoute
  ProposalPreviewRoute: typeof ProposalPreviewRoute
  ProtectedAccessRoute: typeof ProtectedAccessRoute
  ApiReleaseRoute: typeof ApiReleaseRoute
  LenderDrawReviewPrototypeRoute: typeof LenderDrawReviewPrototypeRoute
  LenderDrawReviewSheetPrototypeRoute: typeof LenderDrawReviewSheetPrototypeRoute
  LenderDrawsPrototypeRoute: typeof LenderDrawsPrototypeRoute
  LenderMilestonesPrototypeRoute: typeof LenderMilestonesPrototypeRoute
  LenderOrganizationManagementPrototypeRoute: typeof LenderOrganizationManagementPrototypeRoute
  LenderProposalConfirmationPrototypeRoute: typeof LenderProposalConfirmationPrototypeRoute
  LenderPrototypeRoute: typeof LenderPrototypeRoute
  ProposalClaimClaimTokenRoute: typeof ProposalClaimClaimTokenRoute
  PrototypeActionItemsRoute: typeof PrototypeActionItemsRoute
  PrototypeBuildCollaborationRoute: typeof PrototypeBuildCollaborationRoute
  PrototypeContractorQuotesRoute: typeof PrototypeContractorQuotesRoute
  PrototypeContractorWorkRoute: typeof PrototypeContractorWorkRoute
  PrototypeSystemPostsRoute: typeof PrototypeSystemPostsRoute
  QuoteInvitationMagicTokenRoute: typeof QuoteInvitationMagicTokenRoute
  ApiAuthSignInRoute: typeof ApiAuthSignInRoute
  ApiAuthSignUpRoute: typeof ApiAuthSignUpRoute
  NewsitevisitBuildIdSiteVisitTokenRoute: typeof NewsitevisitBuildIdSiteVisitTokenRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/protected-access': {
      id: '/protected-access'
      path: '/protected-access'
      fullPath: '/protected-access'
      preLoaderRoute: typeof ProtectedAccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal-preview': {
      id: '/proposal-preview'
      path: '/proposal-preview'
      fullPath: '/proposal-preview'
      preLoaderRoute: typeof ProposalPreviewRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/callback': {
      id: '/callback'
      path: '/callback'
      fullPath: '/callback'
      preLoaderRoute: typeof CallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homeowner': {
      id: '/homeowner'
      path: '/homeowner'
      fullPath: '/homeowner'
      preLoaderRoute: typeof HomeownerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor': {
      id: '/contractor'
      path: '/contractor'
      fullPath: '/contractor'
      preLoaderRoute: typeof ContractorRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder-staff': {
      id: '/builder-staff'
      path: '/builder-staff'
      fullPath: '/builder-staff'
      preLoaderRoute: typeof BuilderStaffRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder': {
      id: '/builder'
      path: '/builder'
      fullPath: '/builder'
      preLoaderRoute: typeof BuilderRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/backoffice': {
      id: '/backoffice'
      path: '/backoffice'
      fullPath: '/backoffice'
      preLoaderRoute: typeof BackofficeRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homeowner/': {
      id: '/homeowner/'
      path: '/'
      fullPath: '/homeowner/'
      preLoaderRoute: typeof HomeownerIndexRouteImport
      parentRoute: typeof HomeownerRouteRoute
    }
    '/contractor/': {
      id: '/contractor/'
      path: '/'
      fullPath: '/contractor/'
      preLoaderRoute: typeof ContractorIndexRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/builder/': {
      id: '/builder/'
      path: '/'
      fullPath: '/builder/'
      preLoaderRoute: typeof BuilderIndexRouteImport
      parentRoute: typeof BuilderRouteRoute
    }
    '/builder-staff/': {
      id: '/builder-staff/'
      path: '/'
      fullPath: '/builder-staff/'
      preLoaderRoute: typeof BuilderStaffIndexRouteImport
      parentRoute: typeof BuilderStaffRouteRoute
    }
    '/backoffice/': {
      id: '/backoffice/'
      path: '/'
      fullPath: '/backoffice/'
      preLoaderRoute: typeof BackofficeIndexRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/quote-invitation/$magicToken': {
      id: '/quote-invitation/$magicToken'
      path: '/quote-invitation/$magicToken'
      fullPath: '/quote-invitation/$magicToken'
      preLoaderRoute: typeof QuoteInvitationMagicTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/system-posts': {
      id: '/prototype/system-posts'
      path: '/prototype/system-posts'
      fullPath: '/prototype/system-posts'
      preLoaderRoute: typeof PrototypeSystemPostsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/contractor-work': {
      id: '/prototype/contractor-work'
      path: '/prototype/contractor-work'
      fullPath: '/prototype/contractor-work'
      preLoaderRoute: typeof PrototypeContractorWorkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/contractor-quotes': {
      id: '/prototype/contractor-quotes'
      path: '/prototype/contractor-quotes'
      fullPath: '/prototype/contractor-quotes'
      preLoaderRoute: typeof PrototypeContractorQuotesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/build-collaboration': {
      id: '/prototype/build-collaboration'
      path: '/prototype/build-collaboration'
      fullPath: '/prototype/build-collaboration'
      preLoaderRoute: typeof PrototypeBuildCollaborationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prototype/action-items': {
      id: '/prototype/action-items'
      path: '/prototype/action-items'
      fullPath: '/prototype/action-items'
      preLoaderRoute: typeof PrototypeActionItemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proposal-claim/$claimToken': {
      id: '/proposal-claim/$claimToken'
      path: '/proposal-claim/$claimToken'
      fullPath: '/proposal-claim/$claimToken'
      preLoaderRoute: typeof ProposalClaimClaimTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lender/prototype': {
      id: '/lender/prototype'
      path: '/lender/prototype'
      fullPath: '/lender/prototype'
      preLoaderRoute: typeof LenderPrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lender/proposal-confirmation-prototype': {
      id: '/lender/proposal-confirmation-prototype'
      path: '/lender/proposal-confirmation-prototype'
      fullPath: '/lender/proposal-confirmation-prototype'
      preLoaderRoute: typeof LenderProposalConfirmationPrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lender/organization-management-prototype': {
      id: '/lender/organization-management-prototype'
      path: '/lender/organization-management-prototype'
      fullPath: '/lender/organization-management-prototype'
      preLoaderRoute: typeof LenderOrganizationManagementPrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lender/milestones-prototype': {
      id: '/lender/milestones-prototype'
      path: '/lender/milestones-prototype'
      fullPath: '/lender/milestones-prototype'
      preLoaderRoute: typeof LenderMilestonesPrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lender/draws-prototype': {
      id: '/lender/draws-prototype'
      path: '/lender/draws-prototype'
      fullPath: '/lender/draws-prototype'
      preLoaderRoute: typeof LenderDrawsPrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lender/draw-review-sheet-prototype': {
      id: '/lender/draw-review-sheet-prototype'
      path: '/lender/draw-review-sheet-prototype'
      fullPath: '/lender/draw-review-sheet-prototype'
      preLoaderRoute: typeof LenderDrawReviewSheetPrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lender/draw-review-prototype': {
      id: '/lender/draw-review-prototype'
      path: '/lender/draw-review-prototype'
      fullPath: '/lender/draw-review-prototype'
      preLoaderRoute: typeof LenderDrawReviewPrototypeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contractor/work': {
      id: '/contractor/work'
      path: '/work'
      fullPath: '/contractor/work'
      preLoaderRoute: typeof ContractorWorkRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/contractor/schedule': {
      id: '/contractor/schedule'
      path: '/schedule'
      fullPath: '/contractor/schedule'
      preLoaderRoute: typeof ContractorScheduleRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/contractor/profile': {
      id: '/contractor/profile'
      path: '/profile'
      fullPath: '/contractor/profile'
      preLoaderRoute: typeof ContractorProfileRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/contractor/onboarding': {
      id: '/contractor/onboarding'
      path: '/onboarding'
      fullPath: '/contractor/onboarding'
      preLoaderRoute: typeof ContractorOnboardingRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/contractor/evidence': {
      id: '/contractor/evidence'
      path: '/evidence'
      fullPath: '/contractor/evidence'
      preLoaderRoute: typeof ContractorEvidenceRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/builder/quote-templates': {
      id: '/builder/quote-templates'
      path: '/quote-templates'
      fullPath: '/builder/quote-templates'
      preLoaderRoute: typeof BuilderQuoteTemplatesRouteImport
      parentRoute: typeof BuilderRouteRoute
    }
    '/builder-staff/quote-templates': {
      id: '/builder-staff/quote-templates'
      path: '/quote-templates'
      fullPath: '/builder-staff/quote-templates'
      preLoaderRoute: typeof BuilderStaffQuoteTemplatesRouteImport
      parentRoute: typeof BuilderStaffRouteRoute
    }
    '/backoffice/user-management': {
      id: '/backoffice/user-management'
      path: '/user-management'
      fullPath: '/backoffice/user-management'
      preLoaderRoute: typeof BackofficeUserManagementRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/backoffice/onboard-contractor': {
      id: '/backoffice/onboard-contractor'
      path: '/onboard-contractor'
      fullPath: '/backoffice/onboard-contractor'
      preLoaderRoute: typeof BackofficeOnboardContractorRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/backoffice/onboard-builder': {
      id: '/backoffice/onboard-builder'
      path: '/onboard-builder'
      fullPath: '/backoffice/onboard-builder'
      preLoaderRoute: typeof BackofficeOnboardBuilderRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/backoffice/integrations': {
      id: '/backoffice/integrations'
      path: '/integrations'
      fullPath: '/backoffice/integrations'
      preLoaderRoute: typeof BackofficeIntegrationsRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/api/release': {
      id: '/api/release'
      path: '/api/release'
      fullPath: '/api/release'
      preLoaderRoute: typeof ApiReleaseRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/proposals': {
      id: '/builder/proposals'
      path: '/proposals'
      fullPath: '/builder/proposals'
      preLoaderRoute: typeof BuilderProposalsRouteRouteImport
      parentRoute: typeof BuilderRouteRoute
    }
    '/builder-staff/proposals': {
      id: '/builder-staff/proposals'
      path: '/proposals'
      fullPath: '/builder-staff/proposals'
      preLoaderRoute: typeof BuilderStaffProposalsRouteRouteImport
      parentRoute: typeof BuilderStaffRouteRoute
    }
    '/builder-staff/builds': {
      id: '/builder-staff/builds'
      path: '/builds'
      fullPath: '/builder-staff/builds'
      preLoaderRoute: typeof BuilderStaffBuildsRouteRouteImport
      parentRoute: typeof BuilderStaffRouteRoute
    }
    '/backoffice/site-visits': {
      id: '/backoffice/site-visits'
      path: '/site-visits'
      fullPath: '/backoffice/site-visits'
      preLoaderRoute: typeof BackofficeSiteVisitsRouteRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/backoffice/settings': {
      id: '/backoffice/settings'
      path: '/settings'
      fullPath: '/backoffice/settings'
      preLoaderRoute: typeof BackofficeSettingsRouteRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/backoffice/proposals': {
      id: '/backoffice/proposals'
      path: '/proposals'
      fullPath: '/backoffice/proposals'
      preLoaderRoute: typeof BackofficeProposalsRouteRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/backoffice/draws': {
      id: '/backoffice/draws'
      path: '/draws'
      fullPath: '/backoffice/draws'
      preLoaderRoute: typeof BackofficeDrawsRouteRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/backoffice/contractors': {
      id: '/backoffice/contractors'
      path: '/contractors'
      fullPath: '/backoffice/contractors'
      preLoaderRoute: typeof BackofficeContractorsRouteRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/backoffice/builds': {
      id: '/backoffice/builds'
      path: '/builds'
      fullPath: '/backoffice/builds'
      preLoaderRoute: typeof BackofficeBuildsRouteRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/backoffice/builders': {
      id: '/backoffice/builders'
      path: '/builders'
      fullPath: '/backoffice/builders'
      preLoaderRoute: typeof BackofficeBuildersRouteRouteImport
      parentRoute: typeof BackofficeRouteRoute
    }
    '/contractor/proposals/': {
      id: '/contractor/proposals/'
      path: '/proposals'
      fullPath: '/contractor/proposals/'
      preLoaderRoute: typeof ContractorProposalsIndexRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/contractor/builds/': {
      id: '/contractor/builds/'
      path: '/builds'
      fullPath: '/contractor/builds/'
      preLoaderRoute: typeof ContractorBuildsIndexRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/builder/proposals/': {
      id: '/builder/proposals/'
      path: '/'
      fullPath: '/builder/proposals/'
      preLoaderRoute: typeof BuilderProposalsIndexRouteImport
      parentRoute: typeof BuilderProposalsRouteRoute
    }
    '/builder-staff/proposals/': {
      id: '/builder-staff/proposals/'
      path: '/'
      fullPath: '/builder-staff/proposals/'
      preLoaderRoute: typeof BuilderStaffProposalsIndexRouteImport
      parentRoute: typeof BuilderStaffProposalsRouteRoute
    }
    '/builder-staff/builds/': {
      id: '/builder-staff/builds/'
      path: '/'
      fullPath: '/builder-staff/builds/'
      preLoaderRoute: typeof BuilderStaffBuildsIndexRouteImport
      parentRoute: typeof BuilderStaffBuildsRouteRoute
    }
    '/backoffice/settings/': {
      id: '/backoffice/settings/'
      path: '/'
      fullPath: '/backoffice/settings/'
      preLoaderRoute: typeof BackofficeSettingsIndexRouteImport
      parentRoute: typeof BackofficeSettingsRouteRoute
    }
    '/backoffice/proposals/': {
      id: '/backoffice/proposals/'
      path: '/'
      fullPath: '/backoffice/proposals/'
      preLoaderRoute: typeof BackofficeProposalsIndexRouteImport
      parentRoute: typeof BackofficeProposalsRouteRoute
    }
    '/backoffice/contractors/': {
      id: '/backoffice/contractors/'
      path: '/'
      fullPath: '/backoffice/contractors/'
      preLoaderRoute: typeof BackofficeContractorsIndexRouteImport
      parentRoute: typeof BackofficeContractorsRouteRoute
    }
    '/backoffice/builds/': {
      id: '/backoffice/builds/'
      path: '/'
      fullPath: '/backoffice/builds/'
      preLoaderRoute: typeof BackofficeBuildsIndexRouteImport
      parentRoute: typeof BackofficeBuildsRouteRoute
    }
    '/backoffice/builders/': {
      id: '/backoffice/builders/'
      path: '/'
      fullPath: '/backoffice/builders/'
      preLoaderRoute: typeof BackofficeBuildersIndexRouteImport
      parentRoute: typeof BackofficeBuildersRouteRoute
    }
    '/newsitevisit/$buildId/$siteVisitToken': {
      id: '/newsitevisit/$buildId/$siteVisitToken'
      path: '/newsitevisit/$buildId/$siteVisitToken'
      fullPath: '/newsitevisit/$buildId/$siteVisitToken'
      preLoaderRoute: typeof NewsitevisitBuildIdSiteVisitTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/homeowner/builds/$buildId': {
      id: '/homeowner/builds/$buildId'
      path: '/builds/$buildId'
      fullPath: '/homeowner/builds/$buildId'
      preLoaderRoute: typeof HomeownerBuildsBuildIdRouteImport
      parentRoute: typeof HomeownerRouteRoute
    }
    '/contractor/proposals/$proposalId': {
      id: '/contractor/proposals/$proposalId'
      path: '/proposals/$proposalId'
      fullPath: '/contractor/proposals/$proposalId'
      preLoaderRoute: typeof ContractorProposalsProposalIdRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/contractor/builds/$buildId': {
      id: '/contractor/builds/$buildId'
      path: '/builds/$buildId'
      fullPath: '/contractor/builds/$buildId'
      preLoaderRoute: typeof ContractorBuildsBuildIdRouteImport
      parentRoute: typeof ContractorRouteRoute
    }
    '/builder/proposals/new': {
      id: '/builder/proposals/new'
      path: '/new'
      fullPath: '/builder/proposals/new'
      preLoaderRoute: typeof BuilderProposalsNewRouteImport
      parentRoute: typeof BuilderProposalsRouteRoute
    }
    '/builder/contractors/$contractorId': {
      id: '/builder/contractors/$contractorId'
      path: '/contractors/$contractorId'
      fullPath: '/builder/contractors/$contractorId'
      preLoaderRoute: typeof BuilderContractorsContractorIdRouteImport
      parentRoute: typeof BuilderRouteRoute
    }
    '/backoffice/proposals/unassigned': {
      id: '/backoffice/proposals/unassigned'
      path: '/unassigned'
      fullPath: '/backoffice/proposals/unassigned'
      preLoaderRoute: typeof BackofficeProposalsUnassignedRouteImport
      parentRoute: typeof BackofficeProposalsRouteRoute
    }
    '/backoffice/proposals/review-requirements-prototype': {
      id: '/backoffice/proposals/review-requirements-prototype'
      path: '/review-requirements-prototype'
      fullPath: '/backoffice/proposals/review-requirements-prototype'
      preLoaderRoute: typeof BackofficeProposalsReviewRequirementsPrototypeRouteImport
      parentRoute: typeof BackofficeProposalsRouteRoute
    }
    '/backoffice/proposals/new': {
      id: '/backoffice/proposals/new'
      path: '/new'
      fullPath: '/backoffice/proposals/new'
      preLoaderRoute: typeof BackofficeProposalsNewRouteImport
      parentRoute: typeof BackofficeProposalsRouteRoute
    }
    '/backoffice/proposals/$planId': {
      id: '/backoffice/proposals/$planId'
      path: '/$planId'
      fullPath: '/backoffice/proposals/$planId'
      preLoaderRoute: typeof BackofficeProposalsPlanIdRouteImport
      parentRoute: typeof BackofficeProposalsRouteRoute
    }
    '/backoffice/contractors/onboarding': {
      id: '/backoffice/contractors/onboarding'
      path: '/onboarding'
      fullPath: '/backoffice/contractors/onboarding'
      preLoaderRoute: typeof BackofficeContractorsOnboardingRouteImport
      parentRoute: typeof BackofficeContractorsRouteRoute
    }
    '/backoffice/contractors/$contractorId': {
      id: '/backoffice/contractors/$contractorId'
      path: '/$contractorId'
      fullPath: '/backoffice/contractors/$contractorId'
      preLoaderRoute: typeof BackofficeContractorsContractorIdRouteImport
      parentRoute: typeof BackofficeContractorsRouteRoute
    }
    '/backoffice/builders/builderId': {
      id: '/backoffice/builders/builderId'
      path: '/builderId'
      fullPath: '/backoffice/builders/builderId'
      preLoaderRoute: typeof BackofficeBuildersBuilderIdRouteImport
      parentRoute: typeof BackofficeBuildersRouteRoute
    }
    '/api/auth/sign-up': {
      id: '/api/auth/sign-up'
      path: '/api/auth/sign-up'
      fullPath: '/api/auth/sign-up'
      preLoaderRoute: typeof ApiAuthSignUpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/auth/sign-in': {
      id: '/api/auth/sign-in'
      path: '/api/auth/sign-in'
      fullPath: '/api/auth/sign-in'
      preLoaderRoute: typeof ApiAuthSignInRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/builder/proposals/$proposalId': {
      id: '/builder/proposals/$proposalId'
      path: '/$proposalId'
      fullPath: '/builder/proposals/$proposalId'
      preLoaderRoute: typeof BuilderProposalsProposalIdRouteRouteImport
      parentRoute: typeof BuilderProposalsRouteRoute
    }
    '/builder-staff/proposals/$proposalId': {
      id: '/builder-staff/proposals/$proposalId'
      path: '/$proposalId'
      fullPath: '/builder-staff/proposals/$proposalId'
      preLoaderRoute: typeof BuilderStaffProposalsProposalIdRouteRouteImport
      parentRoute: typeof BuilderStaffProposalsRouteRoute
    }
    '/backoffice/builds/$buildId': {
      id: '/backoffice/builds/$buildId'
      path: '/$buildId'
      fullPath: '/backoffice/builds/$buildId'
      preLoaderRoute: typeof BackofficeBuildsBuildIdRouteRouteImport
      parentRoute: typeof BackofficeBuildsRouteRoute
    }
    '/builder/proposals/$proposalId/': {
      id: '/builder/proposals/$proposalId/'
      path: '/'
      fullPath: '/builder/proposals/$proposalId/'
      preLoaderRoute: typeof BuilderProposalsProposalIdIndexRouteImport
      parentRoute: typeof BuilderProposalsProposalIdRouteRoute
    }
    '/builder/builds/$buildId/': {
      id: '/builder/builds/$buildId/'
      path: '/builds/$buildId'
      fullPath: '/builder/builds/$buildId/'
      preLoaderRoute: typeof BuilderBuildsBuildIdIndexRouteImport
      parentRoute: typeof BuilderRouteRoute
    }
    '/builder-staff/proposals/$proposalId/': {
      id: '/builder-staff/proposals/$proposalId/'
      path: '/'
      fullPath: '/builder-staff/proposals/$proposalId/'
      preLoaderRoute: typeof BuilderStaffProposalsProposalIdIndexRouteImport
      parentRoute: typeof BuilderStaffProposalsProposalIdRouteRoute
    }
    '/builder-staff/builds/$buildId/': {
      id: '/builder-staff/builds/$buildId/'
      path: '/$buildId'
      fullPath: '/builder-staff/builds/$buildId/'
      preLoaderRoute: typeof BuilderStaffBuildsBuildIdIndexRouteImport
      parentRoute: typeof BuilderStaffBuildsRouteRoute
    }
    '/backoffice/builds/$buildId/': {
      id: '/backoffice/builds/$buildId/'
      path: '/'
      fullPath: '/backoffice/builds/$buildId/'
      preLoaderRoute: typeof BackofficeBuildsBuildIdIndexRouteImport
      parentRoute: typeof BackofficeBuildsBuildIdRouteRoute
    }
    '/builder/builds/$buildId/quotes/new': {
      id: '/builder/builds/$buildId/quotes/new'
      path: '/builds/$buildId/quotes/new'
      fullPath: '/builder/builds/$buildId/quotes/new'
      preLoaderRoute: typeof BuilderBuildsBuildIdQuotesNewRouteImport
      parentRoute: typeof BuilderRouteRoute
    }
    '/builder-staff/builds/$buildId/quotes/new': {
      id: '/builder-staff/builds/$buildId/quotes/new'
      path: '/$buildId/quotes/new'
      fullPath: '/builder-staff/builds/$buildId/quotes/new'
      preLoaderRoute: typeof BuilderStaffBuildsBuildIdQuotesNewRouteImport
      parentRoute: typeof BuilderStaffBuildsRouteRoute
    }
    '/backoffice/builds/$buildId/quotes/new': {
      id: '/backoffice/builds/$buildId/quotes/new'
      path: '/quotes/new'
      fullPath: '/backoffice/builds/$buildId/quotes/new'
      preLoaderRoute: typeof BackofficeBuildsBuildIdQuotesNewRouteImport
      parentRoute: typeof BackofficeBuildsBuildIdRouteRoute
    }
  }
}

interface BackofficeBuildersRouteRouteChildren {
  BackofficeBuildersBuilderIdRoute: typeof BackofficeBuildersBuilderIdRoute
  BackofficeBuildersIndexRoute: typeof BackofficeBuildersIndexRoute
}

const BackofficeBuildersRouteRouteChildren: BackofficeBuildersRouteRouteChildren =
  {
    BackofficeBuildersBuilderIdRoute: BackofficeBuildersBuilderIdRoute,
    BackofficeBuildersIndexRoute: BackofficeBuildersIndexRoute,
  }

const BackofficeBuildersRouteRouteWithChildren =
  BackofficeBuildersRouteRoute._addFileChildren(
    BackofficeBuildersRouteRouteChildren,
  )

interface BackofficeBuildsBuildIdRouteRouteChildren {
  BackofficeBuildsBuildIdIndexRoute: typeof BackofficeBuildsBuildIdIndexRoute
  BackofficeBuildsBuildIdQuotesNewRoute: typeof BackofficeBuildsBuildIdQuotesNewRoute
}

const BackofficeBuildsBuildIdRouteRouteChildren: BackofficeBuildsBuildIdRouteRouteChildren =
  {
    BackofficeBuildsBuildIdIndexRoute: BackofficeBuildsBuildIdIndexRoute,
    BackofficeBuildsBuildIdQuotesNewRoute:
      BackofficeBuildsBuildIdQuotesNewRoute,
  }

const BackofficeBuildsBuildIdRouteRouteWithChildren =
  BackofficeBuildsBuildIdRouteRoute._addFileChildren(
    BackofficeBuildsBuildIdRouteRouteChildren,
  )

interface BackofficeBuildsRouteRouteChildren {
  BackofficeBuildsBuildIdRouteRoute: typeof BackofficeBuildsBuildIdRouteRouteWithChildren
  BackofficeBuildsIndexRoute: typeof BackofficeBuildsIndexRoute
}

const BackofficeBuildsRouteRouteChildren: BackofficeBuildsRouteRouteChildren = {
  BackofficeBuildsBuildIdRouteRoute:
    BackofficeBuildsBuildIdRouteRouteWithChildren,
  BackofficeBuildsIndexRoute: BackofficeBuildsIndexRoute,
}

const BackofficeBuildsRouteRouteWithChildren =
  BackofficeBuildsRouteRoute._addFileChildren(
    BackofficeBuildsRouteRouteChildren,
  )

interface BackofficeContractorsRouteRouteChildren {
  BackofficeContractorsContractorIdRoute: typeof BackofficeContractorsContractorIdRoute
  BackofficeContractorsOnboardingRoute: typeof BackofficeContractorsOnboardingRoute
  BackofficeContractorsIndexRoute: typeof BackofficeContractorsIndexRoute
}

const BackofficeContractorsRouteRouteChildren: BackofficeContractorsRouteRouteChildren =
  {
    BackofficeContractorsContractorIdRoute:
      BackofficeContractorsContractorIdRoute,
    BackofficeContractorsOnboardingRoute: BackofficeContractorsOnboardingRoute,
    BackofficeContractorsIndexRoute: BackofficeContractorsIndexRoute,
  }

const BackofficeContractorsRouteRouteWithChildren =
  BackofficeContractorsRouteRoute._addFileChildren(
    BackofficeContractorsRouteRouteChildren,
  )

interface BackofficeProposalsRouteRouteChildren {
  BackofficeProposalsPlanIdRoute: typeof BackofficeProposalsPlanIdRoute
  BackofficeProposalsNewRoute: typeof BackofficeProposalsNewRoute
  BackofficeProposalsReviewRequirementsPrototypeRoute: typeof BackofficeProposalsReviewRequirementsPrototypeRoute
  BackofficeProposalsUnassignedRoute: typeof BackofficeProposalsUnassignedRoute
  BackofficeProposalsIndexRoute: typeof BackofficeProposalsIndexRoute
}

const BackofficeProposalsRouteRouteChildren: BackofficeProposalsRouteRouteChildren =
  {
    BackofficeProposalsPlanIdRoute: BackofficeProposalsPlanIdRoute,
    BackofficeProposalsNewRoute: BackofficeProposalsNewRoute,
    BackofficeProposalsReviewRequirementsPrototypeRoute:
      BackofficeProposalsReviewRequirementsPrototypeRoute,
    BackofficeProposalsUnassignedRoute: BackofficeProposalsUnassignedRoute,
    BackofficeProposalsIndexRoute: BackofficeProposalsIndexRoute,
  }

const BackofficeProposalsRouteRouteWithChildren =
  BackofficeProposalsRouteRoute._addFileChildren(
    BackofficeProposalsRouteRouteChildren,
  )

interface BackofficeSettingsRouteRouteChildren {
  BackofficeSettingsIndexRoute: typeof BackofficeSettingsIndexRoute
}

const BackofficeSettingsRouteRouteChildren: BackofficeSettingsRouteRouteChildren =
  {
    BackofficeSettingsIndexRoute: BackofficeSettingsIndexRoute,
  }

const BackofficeSettingsRouteRouteWithChildren =
  BackofficeSettingsRouteRoute._addFileChildren(
    BackofficeSettingsRouteRouteChildren,
  )

interface BackofficeRouteRouteChildren {
  BackofficeBuildersRouteRoute: typeof BackofficeBuildersRouteRouteWithChildren
  BackofficeBuildsRouteRoute: typeof BackofficeBuildsRouteRouteWithChildren
  BackofficeContractorsRouteRoute: typeof BackofficeContractorsRouteRouteWithChildren
  BackofficeDrawsRouteRoute: typeof BackofficeDrawsRouteRoute
  BackofficeProposalsRouteRoute: typeof BackofficeProposalsRouteRouteWithChildren
  BackofficeSettingsRouteRoute: typeof BackofficeSettingsRouteRouteWithChildren
  BackofficeSiteVisitsRouteRoute: typeof BackofficeSiteVisitsRouteRoute
  BackofficeIntegrationsRoute: typeof BackofficeIntegrationsRoute
  BackofficeOnboardBuilderRoute: typeof BackofficeOnboardBuilderRoute
  BackofficeOnboardContractorRoute: typeof BackofficeOnboardContractorRoute
  BackofficeUserManagementRoute: typeof BackofficeUserManagementRoute
  BackofficeIndexRoute: typeof BackofficeIndexRoute
}

const BackofficeRouteRouteChildren: BackofficeRouteRouteChildren = {
  BackofficeBuildersRouteRoute: BackofficeBuildersRouteRouteWithChildren,
  BackofficeBuildsRouteRoute: BackofficeBuildsRouteRouteWithChildren,
  BackofficeContractorsRouteRoute: BackofficeContractorsRouteRouteWithChildren,
  BackofficeDrawsRouteRoute: BackofficeDrawsRouteRoute,
  BackofficeProposalsRouteRoute: BackofficeProposalsRouteRouteWithChildren,
  BackofficeSettingsRouteRoute: BackofficeSettingsRouteRouteWithChildren,
  BackofficeSiteVisitsRouteRoute: BackofficeSiteVisitsRouteRoute,
  BackofficeIntegrationsRoute: BackofficeIntegrationsRoute,
  BackofficeOnboardBuilderRoute: BackofficeOnboardBuilderRoute,
  BackofficeOnboardContractorRoute: BackofficeOnboardContractorRoute,
  BackofficeUserManagementRoute: BackofficeUserManagementRoute,
  BackofficeIndexRoute: BackofficeIndexRoute,
}

const BackofficeRouteRouteWithChildren = BackofficeRouteRoute._addFileChildren(
  BackofficeRouteRouteChildren,
)

interface BuilderProposalsProposalIdRouteRouteChildren {
  BuilderProposalsProposalIdIndexRoute: typeof BuilderProposalsProposalIdIndexRoute
}

const BuilderProposalsProposalIdRouteRouteChildren: BuilderProposalsProposalIdRouteRouteChildren =
  {
    BuilderProposalsProposalIdIndexRoute: BuilderProposalsProposalIdIndexRoute,
  }

const BuilderProposalsProposalIdRouteRouteWithChildren =
  BuilderProposalsProposalIdRouteRoute._addFileChildren(
    BuilderProposalsProposalIdRouteRouteChildren,
  )

interface BuilderProposalsRouteRouteChildren {
  BuilderProposalsProposalIdRouteRoute: typeof BuilderProposalsProposalIdRouteRouteWithChildren
  BuilderProposalsNewRoute: typeof BuilderProposalsNewRoute
  BuilderProposalsIndexRoute: typeof BuilderProposalsIndexRoute
}

const BuilderProposalsRouteRouteChildren: BuilderProposalsRouteRouteChildren = {
  BuilderProposalsProposalIdRouteRoute:
    BuilderProposalsProposalIdRouteRouteWithChildren,
  BuilderProposalsNewRoute: BuilderProposalsNewRoute,
  BuilderProposalsIndexRoute: BuilderProposalsIndexRoute,
}

const BuilderProposalsRouteRouteWithChildren =
  BuilderProposalsRouteRoute._addFileChildren(
    BuilderProposalsRouteRouteChildren,
  )

interface BuilderRouteRouteChildren {
  BuilderProposalsRouteRoute: typeof BuilderProposalsRouteRouteWithChildren
  BuilderQuoteTemplatesRoute: typeof BuilderQuoteTemplatesRoute
  BuilderIndexRoute: typeof BuilderIndexRoute
  BuilderContractorsContractorIdRoute: typeof BuilderContractorsContractorIdRoute
  BuilderBuildsBuildIdIndexRoute: typeof BuilderBuildsBuildIdIndexRoute
  BuilderBuildsBuildIdQuotesNewRoute: typeof BuilderBuildsBuildIdQuotesNewRoute
}

const BuilderRouteRouteChildren: BuilderRouteRouteChildren = {
  BuilderProposalsRouteRoute: BuilderProposalsRouteRouteWithChildren,
  BuilderQuoteTemplatesRoute: BuilderQuoteTemplatesRoute,
  BuilderIndexRoute: BuilderIndexRoute,
  BuilderContractorsContractorIdRoute: BuilderContractorsContractorIdRoute,
  BuilderBuildsBuildIdIndexRoute: BuilderBuildsBuildIdIndexRoute,
  BuilderBuildsBuildIdQuotesNewRoute: BuilderBuildsBuildIdQuotesNewRoute,
}

const BuilderRouteRouteWithChildren = BuilderRouteRoute._addFileChildren(
  BuilderRouteRouteChildren,
)

interface BuilderStaffBuildsRouteRouteChildren {
  BuilderStaffBuildsIndexRoute: typeof BuilderStaffBuildsIndexRoute
  BuilderStaffBuildsBuildIdIndexRoute: typeof BuilderStaffBuildsBuildIdIndexRoute
  BuilderStaffBuildsBuildIdQuotesNewRoute: typeof BuilderStaffBuildsBuildIdQuotesNewRoute
}

const BuilderStaffBuildsRouteRouteChildren: BuilderStaffBuildsRouteRouteChildren =
  {
    BuilderStaffBuildsIndexRoute: BuilderStaffBuildsIndexRoute,
    BuilderStaffBuildsBuildIdIndexRoute: BuilderStaffBuildsBuildIdIndexRoute,
    BuilderStaffBuildsBuildIdQuotesNewRoute:
      BuilderStaffBuildsBuildIdQuotesNewRoute,
  }

const BuilderStaffBuildsRouteRouteWithChildren =
  BuilderStaffBuildsRouteRoute._addFileChildren(
    BuilderStaffBuildsRouteRouteChildren,
  )

interface BuilderStaffProposalsProposalIdRouteRouteChildren {
  BuilderStaffProposalsProposalIdIndexRoute: typeof BuilderStaffProposalsProposalIdIndexRoute
}

const BuilderStaffProposalsProposalIdRouteRouteChildren: BuilderStaffProposalsProposalIdRouteRouteChildren =
  {
    BuilderStaffProposalsProposalIdIndexRoute:
      BuilderStaffProposalsProposalIdIndexRoute,
  }

const BuilderStaffProposalsProposalIdRouteRouteWithChildren =
  BuilderStaffProposalsProposalIdRouteRoute._addFileChildren(
    BuilderStaffProposalsProposalIdRouteRouteChildren,
  )

interface BuilderStaffProposalsRouteRouteChildren {
  BuilderStaffProposalsProposalIdRouteRoute: typeof BuilderStaffProposalsProposalIdRouteRouteWithChildren
  BuilderStaffProposalsIndexRoute: typeof BuilderStaffProposalsIndexRoute
}

const BuilderStaffProposalsRouteRouteChildren: BuilderStaffProposalsRouteRouteChildren =
  {
    BuilderStaffProposalsProposalIdRouteRoute:
      BuilderStaffProposalsProposalIdRouteRouteWithChildren,
    BuilderStaffProposalsIndexRoute: BuilderStaffProposalsIndexRoute,
  }

const BuilderStaffProposalsRouteRouteWithChildren =
  BuilderStaffProposalsRouteRoute._addFileChildren(
    BuilderStaffProposalsRouteRouteChildren,
  )

interface BuilderStaffRouteRouteChildren {
  BuilderStaffBuildsRouteRoute: typeof BuilderStaffBuildsRouteRouteWithChildren
  BuilderStaffProposalsRouteRoute: typeof BuilderStaffProposalsRouteRouteWithChildren
  BuilderStaffQuoteTemplatesRoute: typeof BuilderStaffQuoteTemplatesRoute
  BuilderStaffIndexRoute: typeof BuilderStaffIndexRoute
}

const BuilderStaffRouteRouteChildren: BuilderStaffRouteRouteChildren = {
  BuilderStaffBuildsRouteRoute: BuilderStaffBuildsRouteRouteWithChildren,
  BuilderStaffProposalsRouteRoute: BuilderStaffProposalsRouteRouteWithChildren,
  BuilderStaffQuoteTemplatesRoute: BuilderStaffQuoteTemplatesRoute,
  BuilderStaffIndexRoute: BuilderStaffIndexRoute,
}

const BuilderStaffRouteRouteWithChildren =
  BuilderStaffRouteRoute._addFileChildren(BuilderStaffRouteRouteChildren)

interface ContractorRouteRouteChildren {
  ContractorEvidenceRoute: typeof ContractorEvidenceRoute
  ContractorOnboardingRoute: typeof ContractorOnboardingRoute
  ContractorProfileRoute: typeof ContractorProfileRoute
  ContractorScheduleRoute: typeof ContractorScheduleRoute
  ContractorWorkRoute: typeof ContractorWorkRoute
  ContractorIndexRoute: typeof ContractorIndexRoute
  ContractorBuildsBuildIdRoute: typeof ContractorBuildsBuildIdRoute
  ContractorProposalsProposalIdRoute: typeof ContractorProposalsProposalIdRoute
  ContractorBuildsIndexRoute: typeof ContractorBuildsIndexRoute
  ContractorProposalsIndexRoute: typeof ContractorProposalsIndexRoute
}

const ContractorRouteRouteChildren: ContractorRouteRouteChildren = {
  ContractorEvidenceRoute: ContractorEvidenceRoute,
  ContractorOnboardingRoute: ContractorOnboardingRoute,
  ContractorProfileRoute: ContractorProfileRoute,
  ContractorScheduleRoute: ContractorScheduleRoute,
  ContractorWorkRoute: ContractorWorkRoute,
  ContractorIndexRoute: ContractorIndexRoute,
  ContractorBuildsBuildIdRoute: ContractorBuildsBuildIdRoute,
  ContractorProposalsProposalIdRoute: ContractorProposalsProposalIdRoute,
  ContractorBuildsIndexRoute: ContractorBuildsIndexRoute,
  ContractorProposalsIndexRoute: ContractorProposalsIndexRoute,
}

const ContractorRouteRouteWithChildren = ContractorRouteRoute._addFileChildren(
  ContractorRouteRouteChildren,
)

interface HomeownerRouteRouteChildren {
  HomeownerIndexRoute: typeof HomeownerIndexRoute
  HomeownerBuildsBuildIdRoute: typeof HomeownerBuildsBuildIdRoute
}

const HomeownerRouteRouteChildren: HomeownerRouteRouteChildren = {
  HomeownerIndexRoute: HomeownerIndexRoute,
  HomeownerBuildsBuildIdRoute: HomeownerBuildsBuildIdRoute,
}

const HomeownerRouteRouteWithChildren = HomeownerRouteRoute._addFileChildren(
  HomeownerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BackofficeRouteRoute: BackofficeRouteRouteWithChildren,
  BuilderRouteRoute: BuilderRouteRouteWithChildren,
  BuilderStaffRouteRoute: BuilderStaffRouteRouteWithChildren,
  ContractorRouteRoute: ContractorRouteRouteWithChildren,
  HomeownerRouteRoute: HomeownerRouteRouteWithChildren,
  CallbackRoute: CallbackRoute,
  ProposalPreviewRoute: ProposalPreviewRoute,
  ProtectedAccessRoute: ProtectedAccessRoute,
  ApiReleaseRoute: ApiReleaseRoute,
  LenderDrawReviewPrototypeRoute: LenderDrawReviewPrototypeRoute,
  LenderDrawReviewSheetPrototypeRoute: LenderDrawReviewSheetPrototypeRoute,
  LenderDrawsPrototypeRoute: LenderDrawsPrototypeRoute,
  LenderMilestonesPrototypeRoute: LenderMilestonesPrototypeRoute,
  LenderOrganizationManagementPrototypeRoute:
    LenderOrganizationManagementPrototypeRoute,
  LenderProposalConfirmationPrototypeRoute:
    LenderProposalConfirmationPrototypeRoute,
  LenderPrototypeRoute: LenderPrototypeRoute,
  ProposalClaimClaimTokenRoute: ProposalClaimClaimTokenRoute,
  PrototypeActionItemsRoute: PrototypeActionItemsRoute,
  PrototypeBuildCollaborationRoute: PrototypeBuildCollaborationRoute,
  PrototypeContractorQuotesRoute: PrototypeContractorQuotesRoute,
  PrototypeContractorWorkRoute: PrototypeContractorWorkRoute,
  PrototypeSystemPostsRoute: PrototypeSystemPostsRoute,
  QuoteInvitationMagicTokenRoute: QuoteInvitationMagicTokenRoute,
  ApiAuthSignInRoute: ApiAuthSignInRoute,
  ApiAuthSignUpRoute: ApiAuthSignUpRoute,
  NewsitevisitBuildIdSiteVisitTokenRoute:
    NewsitevisitBuildIdSiteVisitTokenRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
